### ISSUE TITLE
The document containing the list of use cases for dynamic outputs is not readable

### ISSUE THREAD

**Issue by lberki** [facebook/buck2#103]
There is a document that apparently contains "a full list of worked out use cases" for dynamic dependencies:

https://docs.google.com/document/d/1K8RgvDMvdDFsLWAu0cehauJstHZaFe-7NeaAqWe4-L4/edit

linked from this page:

https://github.com/facebook/buck2/blob/main/docs/rule_authors/dynamic_dependencies.md

The document seems to be a Google Doc, but it's not readable by me (neither with my Google corp Google account nor with my personal one nor in an incognito window)

**Comment by lberki** [comment]
Thanks! As long as there is _something_ I can read to understand dynamic outputs better, I'm happy and the examples you linked seem to fit that bill.

**Comment by ndmitchell** [comment]
I've updated the website at https://buck2.build/docs/rule_authors/dynamic_dependencies/ so it doesn't show the link (it still shows up in the markdown, but hopefully people will start favoring the website once it is more widely advertised). With that and the other links, I'll close this.
