### ISSUE TITLE
Print output path after building a target

### ISSUE THREAD

**Issue by burdiyan** [facebook/buck2#109]
I'm playing around with Buck2 (long time advanced Bazel user). One thing that I immediately missed from Bazel is the ability to easily click the output path in my terminal and open the generated file in my editor. Buck2 doesn't currently print anything to help you find the built file, and I also haven't found any flags to enable that.

**Comment by krallin** [comment]
The flag(s) you're looking for are `--show-output` and `--show-full-output`

**Comment by burdiyan** [comment]
Oh, that's right. Missed that. Any reason why this is not enabled by default?

**Comment by krallin** [comment]
> Any reason why this is not enabled by default?

Hmm, at this point the answer is probably "because buck1 did it this way and that's not something we've taken the time to revisit right now". I know it's not a great answer but that's all I have :)
