### ISSUE TITLE
Self-hosting open-source buck2

### ISSUE THREAD

**Issue by aherrmann** [facebook/buck2#11]
AFAIK the open source version of buck2 can currently only be built with cargo.
Making it self-hosting, i.e. to be able to build the open source buck2 with itself, could be a good milestone on the way to making it useful in open source use-cases. 
This came up in discussion with @arlyon on how to build the open source version of buck2.

**Comment by ndmitchell** [comment]
We can actually build buck2 with buck2, and do in the open source CI.

**Comment by sluongng** [comment]
@ndmitchell Perhaps you would want to adjust the doc in https://github.com/facebook/buck2/blob/f014edfff62a78dc2868c580edb8950f456a65ec/docs/bootstrapping.md a bit.

Especially:

> Note that the resulting binary will be compiled without optimisations or [jemalloc](https://github.com/jemalloc/jemalloc), so we recommend using the Cargo-produced binary in further development.

Does it mean the `buck2 build :buck2` binary now comes with Jemalloc and other optimizations as default?
