### ISSUE TITLE
missing python_library docs?

### ISSUE THREAD

**Issue by jmhodges** [facebook/buck2#111]
The docs for the various python rules ([python_binary](https://buck2.build/docs/generated/starlark/prelude/docs/rules.bzl/#python_binary), [python_test](https://buck2.build/docs/generated/starlark/prelude/docs/rules.bzl/#python_test) and the rest) reference a `python_library` rule. However, there's no python_library documentation on the [Rules API page](https://buck2.build/docs/generated/starlark/prelude/docs/rules.bzl/)

**Comment by ndmitchell** [comment]
We are slowly copying these over from the Buck1 website - https://buck.build/rule/python_library.html#content. The rules are compatible with Buck1, so you can mostly use that for reference. But we do aim to copy them all eventually.

**Comment by ndmitchell** [comment]
Huh, actually, weird - I don't know how python_library got missed from that page. Let me go fix it.

**Comment by ndmitchell** [comment]
Now available at https://buck2.build/docs/api/rules/#python_library thanks to a24de1463f2d5bf1e3eeba8970f22aaae014e71c. Really appreciate the spot!

**Comment by jmhodges** [comment]
Thank you!
