### ISSUE TITLE
feature request: pre-built binaries

### ISSUE THREAD

**Issue by BrianHicks** [facebook/buck2#113]
Hey folks! Now that buck2 has been announced, do you plan on making pre-built binaries available for any platforms, or is it still too early for that? I'd really like to use buck2 at work, but asking everyone to get a Rust toolchain installed to make the build tool may be a bit much still.

**Comment by ndmitchell** [comment]
@themarwhal is hoping to work on this.

**Comment by BrianHicks** [comment]
amazing! 🎉

**Comment by themarwhal** [comment]
added a basic gitub workflow to upload buck2 binaries for a handful of platforms here as a first step: https://github.com/facebook/buck2/actions/workflows/upload_buck2.yml

Will update docs/etc on monday, but latest binaries should be available here for now

**Comment by BrianHicks** [comment]
amazing, thank you!

**Comment by themarwhal** [comment]
The latest builds can be found here: https://github.com/facebook/buck2/releases/tag/latest . Updating docs today.
