### ISSUE TITLE
Where I can point to specific cxx version?

### ISSUE THREAD

**Issue by DaviRain-Su** [facebook/buck2#116]
For example, I want use cxx 20 version.

**Comment by ndmitchell** [comment]
You'd configure that in the toolchain. Looking at our open source examples, https://github.com/facebook/buck2/blob/main/examples/prelude/toolchains/BUCK#L7 defines the toolchain, https://github.com/facebook/buck2/blob/main/prelude/toolchains/cxx.bzl#L100-L107 defines the rule. We seem to have only made link_style configurable thus far, but it should be easy to make other fields like CxxCompilerInfo.compiler_flags configurable tool. Or you can define your own rule (I'd start by copying and pasting system_cxx_toolchain) that does whatever you think is best in terms of toolchain configuration (that's what we do internally at Meta, as quickly the toolchain becomes quite tailored).

**Comment by ndmitchell** [comment]
In fact, let me expose those on system_cxx_toolchain, since its a very common thing to want.

**Comment by DaviRain-Su** [comment]
> In fact, let me expose those on system_cxx_toolchain, since its a very common thing to want.

maybe,It can list examples cpp project for use any cpp version 🤔

**Comment by ndmitchell** [comment]
I think it should be sufficient to do:

```
system_cxx_toolchain(
    name = "cxx",
    cxx_flags = ["-std=c++20"],
    visibility = ["PUBLIC"],
)
```
