### ISSUE TITLE
Are there any plans to suppport more recent versions of Go?

### ISSUE THREAD

**Issue by bbkane** [facebook/buck2#119]
Hello, when reading the Buck2 docs, I found https://buck2.build/docs/api/rules/#go_binary , which states at the end that "Buck currently supports Go version 1.10". Are there plans to support more recent versions of Go? As of today, the most recent version of Go is 1.20.

**Comment by ndmitchell** [comment]
I'm not a Go expert, and we haven't really got any testing for the open source Go rules, so I'd perhaps be sceptical of the documentation and give it a go. I don't know what the outcome will be, but that might uncover other issues.

**Comment by krallin** [comment]
I'll fix up the docs. I also don't think there is that much that is version-dependent in there
