### ISSUE TITLE
Test Execution docs page links to Meta intranet page

### ISSUE THREAD

**Issue by aaronsky** [facebook/buck2#135]
Hi folks, congrats on the launch. I use Buck on an iOS project and was researching how Buck2 could be used in similar ways. While researching how Buck2 handles xctool for test running (and finding that it does not), I noticed that there is a link to a tool called Tpx on [this documentation page](https://buck2.build/docs/rule_authors/test_execution/) that directs towards an internalfb.com site. Will you be making more information about this tool available soon, or open sourcing it?

**Comment by alexlian** [comment]
Thanks for noting this. We've had some internal discussion regarding open sourcing tpx, however that's not in the cards for anytime soon. We'll aim to clean up the tpx reference for now.

Our project generation should probably handle the testing issue via XCode? I'll go get the team to comment here later, and probably add to the docs accordingly.

**Comment by krallin** [comment]
This should be fixed now. We kept the explanation of what Tpx _does_, but we're not linking to it anymore
