### ISSUE TITLE
Test or implement dotnet support

### ISSUE THREAD

**Issue by stevefan1999-personal** [facebook/buck2#137]
[Buck: csharp\_library()](https://buck.build/rule/csharp_library.html)

Seems like Buck used to support C#. Not sure about Buck2 because I didn't see it mentioned in documentations.

**Comment by KapJI** [comment]
Yes, Buck2 currently doesn't support C#. And we don't have plans to add it at this moment, at least for this year.

But if someone submits PR which adds `csharp_library` support to our prelude, we're happy to review it.

**Comment by get9** [comment]
Closing this, but feel free to submit a PR to the prelude with support for `csharp_library` if you like, happy to review it!

**Comment by get9** [comment]
Closing this, but feel free to submit a PR to the prelude with support for `csharp_library` if you like, happy to review it!

**Comment by svermeulen** [comment]
Anyone interested in implementing this probably could learn from the equivalent [bazel rules](https://github.com/bazelbuild/rules_dotnet)
