### ISSUE TITLE
Unreadable directory / Error initializing DaemonStateData

### ISSUE THREAD

**Issue by benbrittain** [facebook/buck2#157]
For _reasons_, there is a directory in my filesystem that I don't have permission to access. It's not beneath the directory containing `.buckconfig` . `FileWatcher` still tries to look at it however and then `buck2` fails to start.

setup:
```
/
/project
/project/other_stuff
/unreadable_dir
```

```
Error initializing DaemonStateData

Caused by:
    0: Error creating a FileWatcher
    1: Permission denied (os error 13) about ["<directory name>"]
    ```

**Comment by krallin** [comment]
> It's not beneath the directory containing .buckconfig

That seems rather odd, what does `buck2 root -k project` yield?

**Comment by krallin** [comment]
Cool, sounds like you must have a `.buckconfig` somewhere up the tree.

> I think that the buck2 init --git command should probably add a .buckroot as well most likely

Sure, that's a good idea. Did you want to send a PR for this? if not I'll submit that.

**Comment by krallin** [comment]
Added support for that in https://github.com/facebook/buck2/commit/54e1eb5e29eca8a021579b859d0a34c73754eb2a
