### ISSUE TITLE
buck2 {clean,kill} and vscode lsp can have some awkward interactions

### ISSUE THREAD

**Issue by thoughtpolice** [facebook/buck2#168]
I have the vscode extension installed now, and I can confirm `buck2 lsp` is in the background. And while doing `buck2 clean` and `buck2 kill` a lot in the process of testing remote execution (because I configure it via root `.buckconfig`, so the daemon needs to restart), I ran into several cases where this caused the `lsp` service in vscode to crash, and in one case nuke the build itself (because vscode got mad at so many restarts, and stopped the lsp from reactivating)

```
austin@GANON:~/src/buck2-nix.sl$ buck build src/hello:
watchman fresh instance event, clearing cache
Build ID: 16e233a4-abc5-42f6-8a67-209d6619856b
Jobs completed: 35. Time elapsed: 4.1s. Cache hits: 0%. Commands: 1 (cached: 0, remote: 0, local: 1)
BUILD FAILED
Command failed: The Buck2 daemon was shut down while executing your command. This happened because: client expected different buckd constraints, caller:
  * /sbin/init
  * /init
  * /init
  * /init
  * sh -c "\"\$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh\" 704ed70d4fd1...
  * sh /mnt/c/Users/jasei/.vscode/extensions/ms-vscode-remote.remote-wsl-0...
  * sh /home/austin/.vscode-server/bin/704ed70d4fd1c6bd6342c436f1ede30d1cf...
  * /home/austin/.vscode-server/bin/704ed70d4fd1c6bd6342c436f1ede30d1cff47...
  * /home/austin/.vscode-server/bin/704ed70d4fd1c6bd6342c436f1ede30d1cff47...
  * buck lsp
  *
```

Note that if you `clean` or `kill` a bunch in a short timeframe, like I said, vscode will get mad and stop new instances from starting. There's also no menu entry to restart the buck2 lsp server.

Also, the lsp server seems to prevent fast execution of `buck clean` itself when I want to re-test some build path, upwards of 5-8 seconds. I realize in a correctly written build `clean` shouldn't be necessary, but still, it's a rather long wait.

There are probably a lot of strange interactions around this that need to be sorted out beyond this.

**Comment by ndmitchell** [comment]
I think the solution is to set an isolation-dir, so that lsp uses a different buck daemon. `buck2 --isolation-dir=lsp lsp` is probably the right command to configure. Does that give you more joy?

**Comment by thoughtpolice** [comment]
I'll give it a shot soon. Do you think it could make that a default, with the default directory created automatically to keep clutter down? For example, imagine if `buck2 lsp` automatically created the dir `$ROOT/buck-out/v2/lsp` and used that as the implicit argument to `--isolation-dir`, by default. That would be great! If you need multiple isolation dirs you'd be on your own then, but just having that default change would be a big deal.

**Comment by thoughtpolice** [comment]
It already does that, under `buck-out/lsp`. My mind has been read; problem solved! Closing.
