### ISSUE TITLE
Rule request: `ios_framework`

### ISSUE THREAD

**Issue by imWildCat** [facebook/buck2#175]
Do we have built-in rule for `ios_framework` which behaves like the iOS framework in Xcode?
I'm thinking about a demo project for iOS. iOS framework seems to be a key component in this demo project.

**Comment by imWildCat** [comment]
Sorry I hit enter by accident. Editing this issue right now

**Comment by alexlian** [comment]
Pre-guessing your request. Internally, we're working on various iOS integrations currently, and we expect to share that out as we get it further along. We hope to get through most of it by end of year.

**Comment by imWildCat** [comment]
@alexlian understand. Thanks for the information!

Looking forward to a roadmap!
