### ISSUE TITLE
Document attrs

### ISSUE THREAD

**Issue by ivwumupy** [facebook/buck2#178]
The `attrs` module is completely incompatible with Bazel. It would be very nice if there are some docs on the detail of `attrs`.

**Comment by thoughtpolice** [comment]
I was looking for this last night and I agree; in the mean time you can look here for all the exported functions, it's 1-to-1: https://github.com/facebook/buck2/blob/abde273eea10c98dfe51c01f3db47832065cf88d/app/buck2_interpreter_for_build/src/attrs/attrs_global.rs#L138

The website has most of the APIs broken down now. I wonder if just adding Rustdoc comments to those functions is enough? I'm not sure if they'll appear on the website then. Or maybe they need a `doc` field somewhere too and something else.

**Comment by ndmitchell** [comment]
Rustdocs is not enough - i'll figure out what is sufficient though.

**Comment by ndmitchell** [comment]
See https://buck2.build/docs/api/build/attrs/ which documents this.
