### ISSUE TITLE
Instance Name Prefix is not plumbed through

### ISSUE THREAD

**Issue by stagnation** [facebook/buck2#180]
Hi

I recently set up buck2 to build with Buildbarn through its[ deployment repository](https://github.com/buildbarn/bb-deployments), and found that the workers with instance name prefixes could not be reached. There is just a hardcoded empty string set in the REAPI calls.

```
remote_execution/oss/re_grpc/src/client.rs
64:const INSTANCE_NAME: &str = "";
284:                    instance_name: INSTANCE_NAME.into(),
319:            instance_name: INSTANCE_NAME.into(),
443:            instance_name: INSTANCE_NAME.into(),
663:        instance_name: INSTANCE_NAME.into(),
```

This is a valuable configuration to keep and target different worker (queues) with a single Buildbarn scheduler.
And this is demonstrated in the example deployment.

For buck2 to successfully schedule action we need to remove that from the deployment at the moment.
See the caveats here: https://github.com/facebook/buck2/pull/179/files#diff-7de77dbbbc29297627446111dde92536735bc8598b81a10520d8ce02fffcb9a7R10-R11
(which will back-link to this discussion)

I think this would be a natural config for the toolchain.
I did some rudimentary hacking to have the toolchain accept this, but I did not proceed to actually plumb it into `re_grpc/src/client.rs`.

So a user could specify the instance name.

```
+++ b/examples/remote_execution/buildbarn/platforms/defs.bzl
@@ -20,6 +20,7 @@ def _platforms(ctx):
         executor_config = CommandExecutorConfig(
             local_enabled = True,
             remote_enabled = True,
+            instance_name_prefix = "fuse",  # or "hardlinking"
             use_limited_hybrid = True,
             remote_execution_properties = {
                 "container-image": image,
```
-------------------------------------------------------------------------------------------------
The prefix is shown in Buildbarn's scheduler 
```
Buildbarn Scheduler                                                                                                 

Build queue
Total number of operations:  0
Platform queues


Instance name                                    Platform properties                                    Size  Timeout   Queued
   prefix                                                                                               class         operatio

"fuse"        OSFamily="Linux" container-image="docker://ghcr.io/catthehacker/                          0     ∞       0
              ubuntu:act-22.04@sha256:5f9c35c25db1d51a8ddaae5c0ba8d3c163c5e9a4a6cc97acd409ac7eae239448"
"hardlinking" OSFamily="Linux" container-image="docker://ghcr.io/catthehacker/                          0     ∞       0
              ubuntu:act-22.04@sha256:5f9c35c25db1d51a8ddaae5c0ba8d3c163c5e9a4a6cc97acd409ac7eae239448"
```

**Comment by thoughtpolice** [comment]
I can try to patch this in; my fix for #170 needs support for `INSTANCE_NAME` too, so it just exacerbates it. I'll try to submit something soon for that.
