### ISSUE TITLE
Provision to get the absolute path to generated binaries/libraries 

### ISSUE THREAD

**Issue by sumeetchhetri** [facebook/buck2#188]
Currently there seems to be no provision to easily fetch the path to the generated artifacts in buck2
Currently it stores the generated artifacts under a directory tree like
`buck-out/v2/gen/root/6553ba90a552c2c0/__{artifact-name}__`
where `6553ba90a552c2c0` is an autogenerated sequence

For CXX builds, if we want to create a final install directory with all artifacts, the output folder should be programmatically available somehow to BUCK2 users with minimum difficulty.

**Comment by dtolnay** [comment]
`buck2 build [TARGETS...] --show-full-output`

It will print one row per top-level target that you requested it to build, with two columns: the label of the target, and the absolute path to the target's output, to stdout.

```console
root//:cxxbridge /git/cxx/buck-out/v2/gen/root/524f8da68ea2a374/__cxxbridge__/static_pic/cxxbridge
```

`--show-output` if you just need a relative path relative to the root of the repo (starting with buck-out/).

**Comment by sumeetchhetri** [comment]
Thanks, it works.

In-fact the command `buck2 build //... --show-full-output` can be used to list all the artifacts generated

**Comment by thoughtpolice** [comment]
Note that if you just want to get the output artifact from a build, `buck build --output <path>` will directly export the output artifact to any file/dir you want. So if you're building an installer, that might be an alternative, too.
