### ISSUE TITLE
Error with prelude based build

### ISSUE THREAD

**Issue by sumeetchhetri** [facebook/buck2#192]
Error initializing DaemonStateData

Caused by:
    cannot find the cell at current path ``. Known roots are `<>`

What could be the reason for this error?
I have correctly created the .buckconfig file and also initiated the `buck2 init --git' command and also have the toolchains folder exactly like https://github.com/facebook/buck2/tree/main/examples/hello_world

Moreover the error should be more user friendly, there is no clue as to what is wrong here.

**Comment by ndmitchell** [comment]
Totally that error message is terrible! I think @stepancheg was improving an error message in that area recently.

Your repo should have a `.buckconfig` file, and one of the entries should be:

```
[repositories]
root = .
```

It uses that to figure out what to call the root cell - you can replace `root` with anything there, but `root` is not a bad default. You can see that code at https://github.com/facebook/buck2/blob/74ee69e1dcdb00f37058e38886d64f93000ad2f5/.buckconfig#L1-L2 for this repo.

**Comment by sumeetchhetri** [comment]
The .buckconfig file was there along with the configuration as you mentioned, I guess the problem was with the symlinks to a private state folder for the workspace and the workspace contents being dynamic in nature. The solution was to do a `buck2 clean` and also instead of `buck2 init --git` which usually may give the dirty state errors, download the prelude folder directly

**Comment by ndmitchell** [comment]
I don't really understand what you mean by a private state folder. But if you've got it working and understand it then perhaps that isn't a problem. Let me know if you think there are things we should do beyond improving the error message.

**Comment by sumeetchhetri** [comment]
So what I understood is Buck maintains a temp [build] folder which is unique for every workspace folder `/Users/{user}/.buck/buckd/private/tmp/{project-path}/v2`, in my case the .buckconfig file was autogenerated and the sequence of generation/command-execution sort-of messed it all up.

On the Improvement front --
1. A better alternative to `buck2 init --git` should be available, the prelude should be auto-fetched by buck whenever mentioned as a dep. 
2. The one better thing in bazel is that you can define paths in a well-defined manner, whereas in buck2 for some weird reason the paths are supposed to be relative which is huge blocker for hierarchical build directories, all the more an issue if you have auto-generated builds

**Buck2 builds are by far the fastest that I have seen yet, really great work by the entire Buck team** 👍 

Currently working on a shell based build tool (provides bazel/buck2 integration) which should be super simple and easy for anyone to start with like here - https://github.com/sumeetchhetri/shellb which is used with a sample project https://github.com/sumeetchhetri/ffead-cpp
