### ISSUE TITLE
Ignoring a directory with FileWatcher

### ISSUE THREAD

**Issue by benbrittain** [facebook/buck2#197]
Is there a way to specify that `FileWatcher` ignore a directory? Maybe in the `.buckconfig`?

For example, making a git commit at the moment currently triggers a file changed alert due to the contents of `.git` changing.

```
File changed: root//.git/index.lock
File changed: root//.git/objects/9f/tmp_obj_P3ikNk
File changed: root//.git/objects/9f/9251bf6abe9c0849768870ee78579b7abeae1a
```

**Comment by benbrittain** [comment]
This seems to work, but it doesn't seem to take array? Would it be possible to extend it so that it can work with more than one directory?

**Comment by cjhopman** [comment]
It should accept a space separated list of directories.

**Comment by benbrittain** [comment]
I can't figure this out unfortunately, 
```
[project]                                                                                                                                        
ignore = ".git"`
`` 
seems to work, but ignore [".git", "other_dir"] returns 

````
1: This error was caused by the end user
 2: error parsing glob '[".git"': unclosed character class; missing ']'
```

and providing a string of comma separated directories results in none of them being ignored.

**Comment by cjhopman** [comment]
Try:

```
[project]
  ignore = .git, other_dir
```

**Comment by cjhopman** [comment]
I checked our actual settings and we do:

```
[project]
  ignore = \
    .git, \
    other_dir
```

I can't imagine that that is required and the single line doesn't work, but i haven't verified it.

**Comment by benbrittain** [comment]
ah, I can confirm it works without the quotes!
