### ISSUE TITLE
what's the best way to manage build scripts in rules?

### ISSUE THREAD

**Issue by BrianHicks** [facebook/buck2#202]
I currently have some build rules like this:

```starlark
def _elm_app_impl(ctx: "context"):
    out = ctx.actions.declare_output(ctx.attrs.out)

    cmd = cmd_args([
        "bash",
        "-xeuo", "pipefail",
        "-c",
        """
        ELM="${1:-}"
        ELM_JSON="${PWD}/${2:-}"
        ELM_MAIN="${PWD}/${3:-}"
        OUT="${PWD}/${4:-}"
        shift 4
        ELM_ARGS="$@"

        cd "$(dirname "$ELM_JSON")"

        $ELM make "$ELM_MAIN" --output "$OUT" $ELM_ARGS
        """,
        "--",
        ctx.attrs._elm_toolchain.get(ElmToolchainInfo).elm,
        ctx.attrs.elm_json,
        ctx.attrs.main,
        out.as_output(),
    ])

    if ctx.attrs.debug:
        ctx.arg("--debug")

    if ctx.attrs.optimize:
        ctx.arg("--optimize")

    cmd.hidden(ctx.attrs.elm_json, ctx.attrs.srcs)
    ctx.actions.run(cmd, category = "elm_app")

    return [DefaultInfo(default_output = out)]

elm_app = rule(
    impl = _elm_app_impl,
    attrs = {
        "out": attrs.string(default="app.js"),
        "elm_json": attrs.source(),
        "main": attrs.source(),
        "srcs": attrs.list(attrs.source()),
        "debug": attrs.bool(default = False),
        "optimize": attrs.bool(default = False),
        "_elm_toolchain": attrs.toolchain_dep(default="toolchains//:elm"),
    }
)
```

If I did that in a `genrule` instead, it looks like it'd be writing that bash script to disk and then executing it instead. That makes me wonder if I'm doing this in a good way, or just in a way that happens to work!

So, the question: is there some pattern that I would be better-advised to follow here or is running `bash -c ...` pretty standard for running build scripts?

**Comment by krallin** [comment]
The way you’re doing it — writing out the script and passing parameters as
args — is what I’d personally describe as  best practice (with the caveat
that if the script gets long you’ll probably want to just have it come from
the disk as a attrs.source()).

An alternative that is sometimes used is trying to compose the command line
using cmd_args, but that commonly runs into escaping issues and generally
the framework being generally oriented towards composing argv rather shell
scripts.

**Comment by BrianHicks** [comment]
ok, I think that makes sense, thanks. This build script is actually gonna get a lot longer—is there a prelude rule that sources a build script with `attrs.source()`? It doesn't look like I can set a default in that?

**Comment by krallin** [comment]
This would typically be something your toolchain should provide. The Python
toolchain has a series of “bootstrap binaries” that are pretty much just
one file for example.

**Comment by krallin** [comment]
I'm sorry, I don't really understand the question here, why do you want to call `genrule` here?
