### ISSUE TITLE
can we have artifact.dirname?

### ISSUE THREAD

**Issue by BrianHicks** [facebook/buck2#205]
`artifact.basename` already exists. I'd like to get `artifact.basename` too. Here's how I'd use it: when building Elm apps, all commands have to kick off from a directory where `elm.json` is present. Just to make things easier, my rules accept an `"elm_json": attrs.source()` as an attr. It doesn't look like there's a nice way to get the dirname of that file right now so I can `cd` to it!

(Of course, I can just pass it into a bash script and call `dirname` there, but it feels hacky to me!)

**Comment by BrianHicks** [comment]
Ah, `relative_to`… seems like that's what we have instead!

```starlark
ctx.actions.write(
    "elm.sh",
    [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        cmd_args(
            elm_json,
            format = "cd $(dirname {})"
        ),
        cmd_args(
            toolchain.elm,
            format = "exec {} $@"
        ).relative_to(elm_json, parent = 1)
    ],
    is_executable = True,
    with_inputs = True,
)
```

**Comment by ndmitchell** [comment]
Perhaps you want `cmd_args.parent` - https://buck2.build/docs/api/build/cmd_args/#cmd_argsparent. It's basically artifact.parent, but it returns a cmd_args, which means you get the string representing the directory (at least when spliced into a command line), but keep the dependency.

**Comment by BrianHicks** [comment]
oh, yeah, I think that's probably exactly what I want. Thank you!

**Comment by ndmitchell** [comment]
Great. I'll add it to the docs for `artifact`.

**Comment by ndmitchell** [comment]
Documented in 50c2306a0987755116c7ed775afcd34bb96ad7af
