### ISSUE TITLE
Links in dice/README.md are dead, or to the wrong project.

### ISSUE THREAD

**Issue by aDotInTheVoid** [facebook/buck2#216]
- <https://github.com/facebookincubator/dice> (and all sub-urls) return 404 for me. I think this is what github does for private repo's, so you probably haven't made it public.
- <https://crates.io/crates/dice> and <https://docs.rs/dice/latest/dice/> are for the unrelated [IvoWingelaar/dice](https://github.com/IvoWingelaar/dice) project.

**Comment by davidbarsky** [comment]
ah, it's been moved. Dice is here: https://github.com/facebook/buck2/tree/main/dice

**Comment by aDotInTheVoid** [comment]
Ah, I assumed it was meant to have a canonical home outside the buck repo, but be vendored in here for dep reasons, like gazebo/superconsole.

**Comment by stepancheg** [comment]
CC @bobyangyf

**Comment by ndmitchell** [comment]
We are planning to open source Dice standalone, in a separate repo, but it hasn't happened yet - once we do it will be like Gazebo/Superconsole/Starlark Rust. For now, the Buck2 location is the only location, at https://github.com/facebook/buck2/tree/main/dice.

**Comment by archshift** [comment]
Any progress on this?

**Comment by ndmitchell** [comment]
Nope - the person who was going to open source DICE moved off the team. @cjhopman now owns it. That said, if you really want DICE all the source code is available in the Buck2 repo. All open sourcing it was going to do was given it a separate home/identity and probably a cargo upload - no additional source code. If you really want the cargo upload, we can do that for you.

**Comment by bobyangyf** [comment]
Yep. I'm no longer working on this.
DICE internals is unfortunately tied with buck2 events so whatever cargo upload we did would still include some buck2 stuff ¯\_(ツ)_/¯

**Comment by ndmitchell** [comment]
Oops, yes, this has got quite entangled with the Buck2 internals. That would be a bit unfortunate (I have no idea what side effects those operations have). Internally I'll rename `move_futures` to `buck2_futures`, so at least the boundary leak is clear.

**Comment by ndmitchell** [comment]
Fixed the docs in 19678f98577799856f05ff9766d0c143d1c52e92 by deleting the links, so closing this one.
