### ISSUE TITLE
cxx_genrule not working

### ISSUE THREAD

**Issue by benbrittain** [facebook/buck2#230]
```
    native.cxx_genrule(                                                                                                  
      name = name,                                                                                                       
      out = proto_obj,                                                                                                   
      srcs = srcs,                                                                                                       
      cmd = "mkdir $OUT; \                                                                                               
              $(exe toolchains//proto:protoc) ${SRCS} --cpp_out $OUT; \                                                   
              $(cxx) ",                                                                                                  
    )
 ```
 
 Results in a error of 
 
 ``` 
Caused by:
    0: Error resolving `$(cxx)`.
    1: There was no mapping for cxx.
 ```

**Comment by cjhopman** [comment]
Hm, that would be expected to come from the c++ toolchain, which should be producing a TemplatePlaceholderInfo with a mapping for cxx. The prelude has a cxx_toolchain_infos function (in prelude/cxx/cxx_toolchain_types.bzl) that sets this up correctly. Maybe the system_cxx_toolchain isn't using that.

**Comment by benbrittain** [comment]
aahh, this might be my fault then. I have a custom C++ toolchain rule. I didn't grok the mechanism for how cxx_genrule works, I can fix that. It looks like the `system_cxx_toolchain` rule does populate this correctly.

**Comment by cjhopman** [comment]
This deserves some user documentation, but the `$(cxx)` support is based on TemplatePlaceholderInfo which has rust doc here: https://github.com/facebook/buck2/blob/50d6df99af3e2b83c3faea1b6bec226fb86adc53/app/buck2_build_api/src/interpreter/rule_defs/provider/builtin/template_placeholder_info.rs#L56

The idea is that any of your deps can provide keys that targets can use in attributes that are `attr.arg()` (so this allows you to extend the system that handles `$(exe)`, `$(location)`, etc). Typically toolchains would provide the "unkeyed" placeholders that are just a single string like `$(cxx)`, and potentially you'd have library or other non-toolchain targets that produce "keyed" placeholders (like maybe cxx_library would support grabbing its shared lib output like `$(cxx_shared_lib //some/cxx:library)`).
