### ISSUE TITLE
Cyclical dependency requires a clean build

### ISSUE THREAD

**Issue by benbrittain** [facebook/buck2#233]
A cyclical dependency where a reference to the target is totally removed does not result in the build "fixing" itself. The  cyclical dependency check continues outputs the deleted target, necessitating a clean build.

**Comment by krallin** [comment]
Yeah that's because there are two cycle detectors ... one that works, and one that works sometimes, and the former isn't enabled by default.

It should be. cc @cjhopman

**Comment by krallin** [comment]
Oh, actually, it looks like it _is_ the default... So no, that's not it.

**Comment by benbrittain** [comment]
Nothing that's public unfortunately, I've had this happen a few times now though, so I'll see if I can put together a small repro.

**Comment by bobyangyf** [comment]
yeah this is probably eager deps, which will be fixed in a few months.

**Comment by krallin** [comment]
> Nothing that's public unfortunately, I've had this happen a few times now though, so I'll see if I can put together a small repro when it happens again.

It's probably not too important, I think we have repros of eager deps causing spurious cycles already (but I'll let Bob correct me if not).

i'll close the issue for now so we don't clutter our issue tracker too much, though we realize it's not "fixed" yet.
