### ISSUE TITLE
Profiling buck2 builds and profiling UX

### ISSUE THREAD

**Issue by thoughtpolice** [facebook/buck2#235]
One of the absolute best features of Shake, IMO, is its support for emitting build profiles &mdash; both as consumable HTML reports with queries over the "lifetime" of the build cycle, as well as individual build commands exporting Chrome-compatible execution traces.

I know `buck2` can profile *itself* to provide memory and CPU reports, but that isn't the same thing obviously. Is there any support for Shake-style build reports, or even just execution traces, as of now? I don't think there are, so I'm filing this issue. I'd really love some features like this in the long run, because they are often indispensable when finding surprising critical paths or observing how traces affect the effectiveness of the execution scheduler. I don't see why the support for this can't go far beyond Shake. There could be many visualizations of the action graph and execution traces. But it's tricky and maybe unclear how it should look, I think.

For example, the (likely widespread) usage of Remote Execution makes this possibly less necessary since presumably you can get metrics from the RE system to solve some of the same issues. On the other hand, the fact that RE exists *at all* might imply some other UX considerations for local `buck2` invocations that are worthy of tracking. In Shake, if a command takes 10 seconds, it takes 10 seconds. But in Buck if an action takes 10 seconds and produces a ~200MB file that itself takes 3 seconds to upload into the cache (whether or not the action was remotely executed or not), both of steps have taken perceptible time. Buck could record this fact (running the command + re upload) and show the time split between the two appropriately. This is also tracked uniformly no matter what RE implementation you use, which is a bonus for end users versus the ops team.

I suspect a lot of the existing Shake HTML profile reports can be applied in some form. Because there's an internal database of state, buck also track the entire "iteration cycle", so it can display aggregate reports about say, `p99` time for a target over all `buck2 build`s, etc.

Also. Because `buck2` maintains an internal database to track state (like Shake does), and a daemon to run builds (unlike Shake) stuffing this feature inside `buck2d` and serving it over a local `http://` endpoint for immediate consumption on all systems would count for extra bonus points.

**Comment by stepancheg** [comment]
`buck` writes machine readable event log (can be viewed with `buck2 log show`). There are spans in it (with references to parent spans). We put a lot of metrics into it, but some important metric may be missing.

This event log can be rendered as Chrome trace with `buck2 debug chrome-trace`.

**Comment by cjhopman** [comment]
> can be viewed with buck2 log show

There's a bunch of other useful log subcommands as well, like `what-ran`, `what-materialized`, `critical-path`, etc. Also, `buck2 debug replay` can replay the superconsole for an event log (with the ability to change the speed, and can enable any of the special more detailed ui just like you could for a normal command).
