### ISSUE TITLE
buck2 uquery is not allowing a query it allowed before

### ISSUE THREAD

**Issue by BrianHicks** [facebook/buck2#236]
In some previous version I was able to run a `uquery` to get all the targets of a particular kind. Now it fails with this message:

```console
$ buck2 uquery 'kind(elm_format_diffs, //...)'
Query args supplied without any `%s` placeholder in the query, got args `//...)`
Build ID: 756d3af8-42f0-4019-88d1-0381d2f65906
Jobs completed: 2. Time elapsed: 0.0s.

$ buck2 --version
buck2 83ebf48be3a03d87b5d62c20c0b8b562 <local>
```

I think this might be some kind of parser regression, because if I remove the space from my query it works fine.

**Comment by cjhopman** [comment]
Hm, that'd have to be a regression in the pretty low level args parsing for it to present that way (i.e. the query parser couldn't do that). Could something have changed about your terminal (or maybe is your buck2 on your PATH some wrapper that may be passing through the args differently?).

**Comment by BrianHicks** [comment]
🤦 yep, that's exactly what's going on. I had been doing it this way for a while but it looks like I cleaned out an old install in `.cargo/bin` so the local script was taking precedence. How annoying!
