### ISSUE TITLE
Improve symlinked_dir() error message

### ISSUE THREAD

**Issue by condemil** [facebook/buck2#238]
When I do

```python
output_dir = ctx.actions.declare_output("out", dir = True)
ctx.actions.symlinked_dir(output_dir, {"x": ctx.actions.declare_output("test")})
```

I see the following error message

```
error: Type of parameter `srcs` doesn't match
```

As I guess the real issue here is that the artifact `test` is unbound, but the error message is misleading.

**Comment by stepancheg** [comment]
What version are you using?

This should have been fixed in https://github.com/facebook/buck2/commit/57e54cd543692eea28f4f1d5af34c21c7c95e9f3

**Comment by condemil** [comment]
You are right, my version was a bit older and I see it is fixed by now. Thank you!
