### ISSUE TITLE
Allow file extension on BUCK files

### ISSUE THREAD

**Issue by Timmmm** [facebook/buck2#243]
Bazel allows you to use `BUILD.bzl` instead of `BUILD`. This is obviously better for various reasons.

Maybe Buck2 should support `BUCK.something` in addition to `BUCK`. `BUCK.bzl` seems weird. As far as I can tell the Starlark extension is `.star` so maybe `BUCK.star`?

A brief search suggests [this might be the place to edit](https://github.com/facebook/buck2/blob/8ef994bd719ed98219cada1d9e2efb82c2d24c5c/app/buck2_core/src/cells/mod.rs#L581).

**Comment by cjhopman** [comment]
You can set the config option buildfile.name to a list of whatever names you want. So for example:

```
[buildfile]
  name = BUCK, BUCK.star
```

And buck will treat the first match it finds as the build file.

In addition, for any configured name, buck will also accept that name + ".v2" with higher precedence (so in the above example it will accept all of "BUCK.v2", "BUCK", "BUCK.star.v2", "BUCK.star" in that order). This is mostly a mechanism for people migrating from buck1 to buck2 that have the rare need to use a completely separate buckfile for v2 vs v1. I think we've mostly used it for defining new things that are only supported in v2 and don't need a buildfile at all for v1.
