### ISSUE TITLE
`--stack` flag is not valid

### ISSUE THREAD

**Issue by inflation** [facebook/buck2#245]
> Attempted to register target toolchains//:cxx twice, re-run the command with `--stack` to obtain a call stack of the first registration

When encountering double definition errors, it would be helpful to see the previous registration as per the error message. But the option is not here.

**Comment by stepancheg** [comment]
Are you running `build` command?

Option is present in query-like commands, but not in `build`.

Try `buck2 ctargets --stack //:target`.

**Comment by stepancheg** [comment]
`--stack` added to all commands, please reopen if the issue persists.
