### ISSUE TITLE
offline-cache does not work as intended

### ISSUE THREAD

**Issue by sluongng** [facebook/buck2#246]
Enabling the offline cache with `buck2.use_network_action_output_cache = true` would resulting in a fail build

```
> buck2 clean

> buck2 build prelude//go/tools:testmaingen2
Watchman fresh instance: cleared graph state
Action failed: anon//:http_archive@1b34881e73f7aa00 (download_file archive.tar.gz)
Internal error: Missing offline cache entry: `buck-out/v2/offline-cache-anon/anon/213ed1b7ab8693791b34881e73f7aa00/__http_archive__/archive.tar.gz`
Build ID: 14ed88bd-67e4-4a55-a75c-c61634626fb8
Jobs completed: 43. Time elapsed: 0.7s.
BUILD FAILED
Failed to build 'anon//:http_archive (anon: 1b34881e73f7aa00) (prelude//platforms:default#213ed1b7ab869379)'
exit 2
```

It seems like the code path was returning too early when the archive is not found in offline-cache, instead of trying to fallback to a download.

This patch fixes that behavior

```
--- a/app/buck2_action_impl/src/actions/impls/download_file.rs
+++ b/app/buck2_action_impl/src/actions/impls/download_file.rs
@@ -254,7 +254,12 @@ impl IncrementalActionExecutable for DownloadFileAction {
         //
         // This mostly looks like a "copy" action.
         if ctx.run_action_knobs().use_network_action_output_cache {
-            return self.execute_for_offline(ctx).await;
+            match self.execute_for_offline(ctx).await {
+                Ok((outputs, metadata)) => {
+                    return Ok((outputs, metadata));
+                }
+                Err(_) => {}
+            }
         }

         let client = http_client()?;
```

(same need to be apply to `CasArtifactAction`)

---

After that, I realized that there is some problem with writing into the cache directory:
1. Without a valid `TracingIoProvider`, the cache will never be populated. This require `export ENABLE_TRACE_IO=1` to be set in environment variable.

2. If `Deferred Materialization` is used, either `deferred` or `deferred_skip_final_artifacts`, the cache will never be written.

Here is a very naive diff to fix (1)
```
@@ -321,7 +326,13 @@ impl IncrementalActionExecutable for DownloadFileAction {
             let offline_cache_path =
                 offline::declare_copy_to_offline_output_cache(ctx, self.output(), value.dupe())
                     .await?;
+            println!("DEBUG: {}", offline_cache_path);
             tracer.add_buck_out_entry(offline_cache_path);
+        } else {
+            let offline_cache_path =
+                offline::declare_copy_to_offline_output_cache(ctx, self.output(), value.dupe())
+                    .await?;
+            println!("DEBUG2: {}", offline_cache_path);
         }

         Ok((
```

Not quite sure how to fix (2) just yet. Perhaps we need to switch from using `Materializer.declare_copy()` to just direct copy?

**Comment by krallin** [comment]
I think the problem here is rather a documentation issue. What you're trying to do is very much no the use case said cache is for.

**Comment by sluongng** [comment]
That would be disappointing.

In Bazel side, there are `--disk_cache=` and `--repository_cache=` to help store the AC/CAS and external downloads locally. I kinda understand that `--disk_cache=` is not desirable in Buck2 for it being "remote exec first", but `repository_cache` is still much needed given how `http_archive` is set to local-only at the moment 🤔 

```
def http_archive_impl(ctx: "context") -> ["provider"]:
    expect(len(ctx.attrs.urls) == 1, "multiple `urls` not support: {}".format(ctx.attrs.urls))

    # The HTTP download is local so it makes little sense to run actions
    # remotely, unless we can defer them.
    local_only = ctx.attrs.sha1 == None
    ...
```

Let me give the sqlite config a try as well.

**Comment by krallin** [comment]
> That would be disappointing.

I'm not following. It's not the feature you need for the thing you want, but the feature you want _does_ in fact exist, so presumably you should use taht?

(though my guess is that the "is it SHA1?" part might be an issue since that assumes the hash scheme is SHA1, which in the OSS built isin't)

**Comment by sluongng** [comment]
I tried it out this morning with these config

```
> cat .buckconfig
[repositories]
root = .
prelude = prelude
shim = shim

[repository_aliases]
config = prelude
ovr_config = prelude
toolchains = shim
fbcode = shim
fbcode_macros = shim
fbsource = shim
buck = shim

[build]
execution_platforms = prelude//platforms:default

[parser]
target_platform_detector_spec = target:root//...->prelude//platforms:default target:shim//...->prelude//platforms:default target:prelude//...->prelude//platforms:default

[buck2]
defer_write_actions = true
sqlite_materializer_state = true
materializations = deferred
```

The file is indeed inside my buck-out directory

```
> fd tar.gz buck-out
buck-out/v2/gen-anon/anon/213ed1b7ab8693791b34881e73f7aa00/__http_archive__/archive.tar.gz
```

And it seems to be recorded by deferred-materializer
```
> buck2 audit deferred-materializer list
Build ID: e9f7a262-7e70-4175-b8d6-b23447a6f3a8
Jobs completed: 0. Time elapsed: 0.0s.
buck-out/v2/gen-anon/anon/213ed1b7ab8693791b34881e73f7aa00/__http_archive__/http_archive        materialized (ts=2023-05-09T18:13:18Z, size=242335882)
buck-out/v2/gen-anon/anon/213ed1b7ab8693791b34881e73f7aa00/__http_archive__/unpack.sh   materialized (ts=2023-05-09T18:13:14Z, size=244)
buck-out/v2/gen/prelude/213ed1b7ab869379/go/tools/__testmaingen2__/build.sh     materialized (ts=2023-05-09T18:13:18Z, size=338)
buck-out/v2/gen/prelude/213ed1b7ab869379/go/tools/__testmaingen2__/main materialized (ts=2023-05-09T18:13:19Z, size=4236818)
buck-out/v2/gen/prelude/213ed1b7ab869379/go/tools/__testmaingen2__/gocache      materialized (ts=2023-05-09T18:13:19Z, size=41737291)
```

But after shutting down wifi/network, I cannot run the build
```
> buck2 build prelude//go/tools:testmaingen2
Action failed: anon//:http_archive@1b34881e73f7aa00 (download_file archive.tar.gz)
Internal error: Error performing a http_download request: HTTP Transfer Error when querying URL: https://dl.google.com/go/go1.20.4.darwin-arm64.tar.gz. Failed before receiving headers.: error sending request for url (https://dl.google.com/go/go1.20.4.darwin-arm64.tar.gz): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known: error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known: dns error: failed to lookup address information: nodename nor servname provided, or not known: failed to lookup address information: nodename nor servname provided, or not known
Build ID: a51bf05e-59b2-46ed-aae3-12e2f8161a48
Jobs completed: 43. Time elapsed: 0.0s.
BUILD FAILED
Failed to build 'anon//:http_archive (anon: 1b34881e73f7aa00) (prelude//platforms:default#213ed1b7ab869379)'
exit 2
```

Here is the code that I am using https://github.com/facebook/buck2/compare/main...sluongng:buck2:sluongng/remote-go-toolchain.

Perhaps I have set the wrong expectation for a remote-exec first build tool? 🤔

**Comment by krallin** [comment]
> But after shutting down wifi/network, I cannot run the build

That I don't think would work as of today — we'll at least do a head request for it. That doesn't seem to be the problem here however.

That said, I expect there's some changes needed to support HTTP deferral (which is what we'd call omitting downloads). In particular, the code in `download_file.rs` only enables this when SHA1 is supported:

```
        if !digest_config.cas_digest_config().allows_sha1() {
            return Ok(None);
        }

        let sha1 = match self.inner.checksum.sha1() {
            Some(sha1) => sha1,
            _ => return Ok(None),
        };

        let sha1 = match RawDigest::parse_sha1(sha1.as_bytes()) {
            Ok(sha1) => sha1,
            Err(_) => return Ok(None),
        };

```

I think this needs to be come something more like:

```
let raw_digest = if digest_config.cas_digest_config().allows_sha1()  {
        let sha1 = match self.inner.checksum.sha1() {
            Some(sha1) => sha1,
            _ => return Ok(None),
        };

        let sha1 = match RawDigest::parse_sha1(sha1.as_bytes()) {
            Ok(sha1) => sha1,
            Err(_) => return Ok(None),
        };

       sha1
} else if digest_config.cas_digest_config().allows_sha256()  {
     // Same as above, but with sha256
} else {
  return Ok(None)
}
```

And then I'd expect it to work

That code might also benefit from some logging, but at least the event log should indicate whether the action was skipped or not

**Comment by krallin** [comment]
> Yeah, that's a mismatch against my expectation.

Fair enough, I'm just trying to tell you what's there and what's not, and that's a thing that's not there.

> Upon a buck daemon reset, we should not expect a user to send HEAD requests to all of these resources.

I do think that bit is debatable. Finding out when your dependencies stop existing can actually be useful (rather than finding out when your new hire can't build anything because unlike you, their cache isn't primed).

> I see use_network_action_output_cache is almost there in implementing it.

Not really. I don't think you noted that, but that cache doesn't actually check whether the cached entry matches what you're trying to download (because that's not what it's for), so just applying the fixes mentioned earlier in this issue wouldn't really give you what you're after.

> I think having an "offline cache for downloaded archives" (and potentially CAS objects) would make buck2 a lot more friendly toward the open-source eco-system.

Are we only talking about omitting the HEAD requests here? If so it seems like making that configurable would be a simpler approach, no?

**Comment by krallin** [comment]
> I think this needs to be come something more like: [...]

That was introduced in https://github.com/facebook/buck2/commit/dfd4362cfed3f42cc7655fbdce1f1c36967c08e1

I'll close this for now on the assumption that this does resolve your issue, but if it doesn't feel free to reopen
