### ISSUE TITLE
how can I improve RE performance?

### ISSUE THREAD

**Issue by BrianHicks** [facebook/buck2#249]
Hey! Thanks to the infrastructure team at work, I've got a shiny new Buildbarn cluster running in Kubernetes. I've tried a couple things to smoke-test it (hello worlds, etc.) and it's working fine. It's just that it's slower than I'd like. For example, requesting `//:elm_version` in the attached starlark snippet takes 2.4s from an empty cache locally, but took 86.1s to run using the remote execution engine. I'm not even sure where to start looking to find out how to diagnose this difference; where would you suggest?

```starlark
ELM_COMPILER_URL = select({
    "config//os:linux": "https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz",
    "config//os:macos": "https://github.com/elm/compiler/releases/download/0.19.1/binary-for-mac-64-bit.gz",
})

ELM_COMPILER_SHA256 = select({
    "config//os:linux": "e44af52bb27f725a973478e589d990a6428e115fe1bb14f03833134d6c0f155c",
    "config//os:macos": "05289f0e3d4f30033487c05e689964c3bb17c0c48012510dbef1df43868545d1",
})

http_file(
    name = "elm_compiler_archive",
    urls = [ELM_COMPILER_URL],
    sha256 = ELM_COMPILER_SHA256,
)

genrule(
    name = "elm_compiler_binary",
    cmd = "gzip --decompress --stdout --keep $(location :elm_compiler_archive) > $OUT && chmod +x $OUT",
    out = "elm",
    executable = True,
    remote = True,
    visibility = ["PUBLIC"],
)

genrule(
    name = "elm_version",
    out = "version.txt",
    cmd = "$(exe :elm_compiler_binary) --version > $OUT",
    remote = True,
)
```

Here, also, is my remote executor config. Maybe there's something in here that's slowing me down?

```starlark
def _platforms_impl(ctx: "context") -> [[DefaultInfo.type, ExecutionPlatformRegistrationInfo.type]]:
    constraints = dict()
    constraints.update(ctx.attrs.os_configuration[ConfigurationInfo].constraints)
    constraints.update(ctx.attrs.arch_configuration[ConfigurationInfo].constraints)

    configuration = ConfigurationInfo(
        constraints = constraints,
        values = {},
    )

    platform = ExecutionPlatformInfo(
        label = ctx.label.raw_target(),
        configuration = configuration,
        executor_config = CommandExecutorConfig(
            local_enabled = True,
            remote_enabled = True,
            use_limited_hybrid = True,
            remote_cache_enabled = True,
            allow_cache_uploads = True,
            # Set those up based on what workers you've registered with Buildbarn.
            remote_execution_properties = {
                "OSFamily": "Linux",
                "container-image": "docker://ghcr.io/catthehacker/ubuntu:act-22.04@sha256:5f9c35c25db1d51a8ddaae5c0ba8d3c163c5e9a4a6cc97acd409ac7eae239448",
            },
            remote_execution_use_case = "buck2-default",
            remote_output_paths = "output_paths",
        ),
    )

    return [
        DefaultInfo(),
        ExecutionPlatformRegistrationInfo(platforms = [platform]),
    ]

platforms = rule(
    impl = _platforms_impl,
    attrs = {
        "os_configuration": attrs.dep(
            providers = [ConfigurationInfo],
            default = "prelude//os:linux",
        ),
        "arch_configuration": attrs.dep(
            providers = [ConfigurationInfo],
            default = "prelude//cpu:x86_64",
        ),
    },
)
```

**Comment by BrianHicks** [comment]
OK, so I looked around a bit more in the issue tracker and found the ability to export a trace. Looks like it's uploading for-ev-er. Probably something to take to my infra team. I'd still love to know if there are better ways to figure this out, or to see the total payload and kb/s metrics so I'll know if our tuning worked!

**Comment by BrianHicks** [comment]
ok, happened across `buck2 log what-uploaded`, which shows this:

```
Showing uploads from: buck-out/buck2 build //:elm_version
root//:elm_version (prelude//platforms:default#6553ba90a552c2c0) (genrule)     16       28394526
total: digests: 16, bytes: 28394526
```

I have no idea why it would be uploading ~3mb for this? Is it uploading the compiler binary every time? Wouldn't the RE already have that? 🤔

**Comment by BrianHicks** [comment]
OK, I have now also learned about `buck2 log critical-path`! Hooray for me. I am really liking all the introspection tools available here; thank you all for adding such good stuff. Anyway, here's what it says:

```
load	root//			951	951	
analysis	root//:elm_version (prelude//platforms:default#6553ba90a552c2c0)			247	247	
action	root//:elm_version (prelude//platforms:default#6553ba90a552c2c0)	write	sh/genrule.sh	397	381	
action	root//:elm_version (prelude//platforms:default#6553ba90a552c2c0)	genrule		27436455	20257	
materialization	root//:elm_version (prelude//platforms:default#6553ba90a552c2c0)		out/version.txt	5	5	
compute-critical-path				52	0	52
```

So that looks like… the `genrule` is taking, what, 27,436,455 bytes and 20,257 digests? That seems like a lot? Is there a way to get more info about what exactly was in that 27mb upload?

**Comment by thoughtpolice** [comment]
Note that's ~28megabytes not 3mb for that `:elm_version` step, and that's approximately the size of the elm compiler binary when decompressed. I think one problem is that remote builds upload intermediate steps back into the cache for usage in subsequent steps?

I think what you need the deferred materializer, which will ensure that intermediate steps are not downloaded and re-uploaded back into the cache. Maybe something like this in your root `.buckconfig`:

```
[buck2]
digest_algorithms = SHA256
materializations = deferred
sqlite_materializer_state = true
defer_write_actions = true
hash_all_commands = true
restarter = true
```

I think I tried this recently but the deferred materializer may be broken in some cases. Might have been fallout from recent changes to fix large uploads; the default open source RE system is pretty MVP right now...

**Comment by krallin** [comment]
> So that looks like… the genrule is taking, what, 27,436,455 bytes and 20,257 digests? That seems like a lot? Is there a way to get more info about what exactly was in that 27mb upload?

Err, this is confusing. The help for that command is wrong, those are durations... I had a diff to fix that, but it seems I forgot to land it.

**Comment by krallin** [comment]
> I think I tried this recently but the deferred materializer may be broken in some cases

What were the issues you hit?

**Comment by krallin** [comment]
The broken `--help` should be fixed in here: https://github.com/facebook/buck2/commit/05a45c2cc9debc4e26c9c2284801fea05c4b9052

**Comment by BrianHicks** [comment]
ah, yeah, doesn't work for me. I think because of [the open-source RE backend problem mentioned in the docs](https://buck2.build/docs/advanced/deferred_materialization/#pitfalls):

> At Meta, artifacts get periodically refreshed, but open source RE backends do not expose the TTL of artifacts, so this feature does not work outside of Meta.

And indeed, when I run this on a fresh target I get an error:

```
Internal error (stage: remote_upload_error): Remote Execution Error (GRPC-SESSION-ID): ae645d3ff3d2fbe87460c077f644d3d64de87b5c40e5dbadd8bb08978148a117:26554336 (expires = 2023-05-12 13:14:30 UTC) is missing in the CAS but expected to exist as per: The artifact at path 'buck-out/v2/gen/prelude-nri/6553ba90a552c2c0/elm/__elm_compiler_binary__/out/elm' (File(ae645d3ff3d2fbe87460c077f644d3d64de87b5c40e5dbadd8bb08978148a117:26554336)) was produced by a RE action (791f31270e9de34dfdded7ae289d4139bad024018227ff5deef443d530f91188:142 retrieved 0 seconds ago with ttl = 0 seconds), but has not been downloaded
```

**Comment by krallin** [comment]
> ah, yeah, doesn't work for me. I think because of [the open-source RE backend problem mentioned in the docs](https://buck2.build/docs/advanced/deferred_materialization/#pitfalls):

I think this is a different problem actually, but I have a fix coming up for it

**Comment by BrianHicks** [comment]
Yeah, it does! Now it fails much faster. 😆 (Somehow it's trying to run a macOS binary on the Linux executor. I suspect something about [my real code](https://github.com/NoRedInk/noredink-ui/blob/master/prelude-nri/elm/BUCK) is specifying the wrong platform.)

**Comment by krallin** [comment]
Good, this should also fix the problem mentioned earlier:

> I have no idea why it would be uploading ~3mb for this? Is it uploading the compiler binary every time? Wouldn't the RE already have that? 🤔

**Comment by krallin** [comment]
> 😆 (Somehow it's trying to run a macOS binary on the Linux executor. I suspect something about [my real code](https://github.com/NoRedInk/noredink-ui/blob/master/prelude-nri/elm/BUCK) is specifying the wrong platform

Does your execution platform specify the right constraints? I can't find where you've defined it in that code (maybe it's on a branch?)

**Comment by krallin** [comment]
The platform you got here should work but it's evidently not the one you're using since that's not got remote enabled. I expect you need to merge that and the one you got for RE

https://github.com/NoRedInk/noredink-ui/blob/master/prelude/platforms/defs.bzl

**Comment by BrianHicks** [comment]
Oh, I'm not using that one. I didn't know it was in the prelude, actually! I'm running the executor that's in that second code sample above. The "real code" link is in a different root, though… do I need to specify which platform the rules produce or something?

**Comment by krallin** [comment]
>  I'm running the executor that's in that second code sample above. 

Do you have the BUCK file that's actually calling this?

**Comment by BrianHicks** [comment]
There are a couple of BUCK files involved here, so I'm not sure which you mean? I just pushed the branch with all my changes to https://github.com/NoRedInk/noredink-ui/pull/1394. The RE platform is defined in `toolchains/platforms.bzl`, referenced in `toolchains/BUCK`, and configured in `.buckconfig`.

**Comment by krallin** [comment]
> referenced in toolchains/BUCK

Yeah that's what I was asking about

I think it'd be a good idea to open a new issue for this. I think there's something misconfigured in your platform setup but I' not 100% sure what it is. 

It would probably help if you shared the exact error output and then looked at `buck2 audit configurations` and `buck2 audit execution-platform-resolution TARGET_THAT_FAILS`

**Comment by BrianHicks** [comment]
OK, I've opened #254 with that info
