### ISSUE TITLE
Add .buckconfig documentation

### ISSUE THREAD

**Issue by sluongng** [facebook/buck2#250]
There is a lack of documentation for the options available in `.buckconfig`. This led to folks searching the code base to discover new config knobs. This also led to miss usages of some config values, a prime example being https://github.com/facebook/buck2/issues/246

Please provide a templated (commented out) config file with all the default values available. Additional comments explaining what each config does would be much appreciated.

**Comment by thoughtpolice** [comment]
Dupe of #152 more or less, I think. Would love to see this though!

**Comment by sluongng** [comment]
Lets close this dupe 😄
