### ISSUE TITLE
resource documentation

### ISSUE THREAD

**Issue by benbrittain** [facebook/buck2#252]
I'm trying to get `cxx_test` working with tests that depend on external resources.

My expectation was anything in the mapping would be placed in tree and accessible to the test, but instead the test is run without a `chdir` and a .json mapping file is created.

What is the canonical way of getting these files into your test? We're gonna need to maintain two build systems in parallel for a while and this seems like it might be a pretty intrusive change?

**Comment by krallin** [comment]
> My expectation was anything in the mapping would be placed in tree and accessible to the test, but instead the test is run without a chdir and a .json mapping file is created.

Read the JSON file hat is next to the binary, and then the paths in there relative to said binary
