### ISSUE TITLE
RBE: sh_test test script for should be prefixed with `./`

### ISSUE THREAD

**Issue by sluongng** [facebook/buck2#255]
Setup a simple sh_test like this

```
sh_test(
    name = "test",
    test = "test.sh",
    args = ["$(location :xyz)", XYZ_SHA256],
)
```

And try to run it against BuildBuddy RBE and we would get this error

```
> buck2 test --unstable-allow-all-tests-on-re :test
✗ Fail: root//:test (0.0s)
---- STDOUT ----

---- STDERR ----
Remote Execution Error (GRPC-SESSION-ID)

Caused by:
    0: RE: execution with digest 62cfd1c66c57c0bf30244ff00330e8b66b16fea36157863f068beed06232fe9f:142
    1: Error was returned on the stream by RE
    2: exec: "test.sh": executable file not found in $PATH
Build ID: 2561efc4-7feb-4dfd-afb6-ce0907d9df05
RE: GRPC-SESSION-ID
Jobs completed: 3. Time elapsed: 1.1s.
Tests finished: Pass 0. Fail 1. Fatal 0. Skip 0. Build failure 0
1 TESTS FAILED
  ✗ root//:test
exit 32
```

Inspecting the Command proto gave me something like this

```
{
  "arguments":  [
    "test.sh",
    "buck-out/v2/gen/root/213ed1b7ab869379/__xyz__/out/xyz.txt",
    "72036ae48c55d632cc333cac04c78be336b0c76f39b225d023e218efe077ab1b"
  ],
  "platform":  {
    "properties":  [
      {
        "name":  "OSFamily",
        "value":  "Linux"
      },
      {
        "name":  "container-image",
        "value":  "docker://gcr.io/flame-public/rbe-ubuntu20-04:latest"
      },
      {
        "name":  "recycle-runner",
        "value":  "true"
      },
      {
        "name":  "workload-isolation-type",
        "value":  "firecracker"
      }
    ]
  }
}
```

So the shell session thought `test.sh` to be a binary in `$PATH` and tried to find it, but couldn't.

Dirty patching prelude with this allowed the test to pass on RBE:

```
prelude> git diff
diff --git a/sh_test.bzl b/sh_test.bzl
index cec8c21..f17bbda 100644
--- a/sh_test.bzl
+++ b/sh_test.bzl
@@ -18,7 +18,7 @@ def sh_test_impl(ctx: "context") -> ["provider"]:

     if ctx.attrs.test != None:
         if type(ctx.attrs.test) == "artifact":
-            args.add(ctx.attrs.test)
+            args.add(cmd_args(["./", ctx.attrs.test], delimiter = ""))
         elif type(ctx.attrs.test) == "dependency":
             run_info = ctx.attrs.test.get(RunInfo)
             if run_info != None:
```

Test result
```
> buck2 test --unstable-allow-all-tests-on-re :test
File changed: root//
File changed: root//.watchman-cookie-Sons-Laptop.local-906-1241
File changed: prelude//sh_test.bzl
6 additional file change events
run_from_project_root: False
✓ Pass: root//:test (4.1s)
---- STDOUT ----

---- STDERR ----

Build ID: 6a77c261-a327-4c97-8759-a02ea6a165ed
RE: GRPC-SESSION-ID
Jobs completed: 12 K. Time elapsed: 6.5s. Cache hits: 100%. Commands: 3001 (cached: 3001, remote: 0, local: 0)
Tests finished: Pass 1. Fail 0. Fatal 0. Skip 0. Build failure 0
```

**Comment by krallin** [comment]
That sounds reasonable, did you want to send a PR?

**Comment by sluongng** [comment]
I was not sure about what would be the right solution for this problem.

Adding a `./` prefix in starlark code fixed it for me, but that's probably the wrong solution for windows users 🤔. I was also wondering if there is a more generic solution inside the `cmd_args` implementation when printing out an artifact input.

If you are happy with the change as-is, let me create a PR 👍

**Comment by sluongng** [comment]
Ultimately, I think what I am looking for is a set of tests to run against to quickly validate changes like this.

**Comment by krallin** [comment]
Yeah, a more principled fix may be for us to render paths to artifacts with
no leading slashes as ./artifact, assuming unix paths (that information is
available when rendering paths).

That’s probably easier than this, I can take a look unless you’d like to.
I’m not at a computer right now, resolve_source might be a good keyword to
get started with

**Comment by sluongng** [comment]
It's bedtime for me in EU but I will take a look if I have the time tomorrow 👀 
If anyone else is interested, feel free to beat me to it 🤗

**Comment by sluongng** [comment]
I don't think this was fixed.
I still have to apply the same workaround today otherwise my remote executor will complain

```
✗ Fail: root//:test (0.5s)
---- STDOUT ----

---- STDERR ----
Error: runc: runc create failed: unable to start container process: exec: "./<source test.sh>": stat ./<source test.sh>: no such file or directory: OCI runtime attempted to invoke a command that was not found
```

Referencing RE API https://github.com/bazelbuild/remote-apis/blob/eafa1b0d7883ffef6520cfd5fd5ff7731b7d55d7/build/bazel/remote/execution/v2/remote_execution.proto#L558-L573, I think it's reasonable to expect `./` to signal to remote executor that we are using relative path here and are not looking up `test.sh` in `$PATH`.

It would be nice if you folks could publish your tests for prelude, that way I could help add a test to verify the RE API request.

**Comment by krallin** [comment]
Yeah, that makes sense, that change was only for local, I'm not sure what I was thinking.

I'll put up a fix.
