### ISSUE TITLE
`run_from_project_root = False` is not running from cell root

### ISSUE THREAD

**Issue by BrianHicks** [facebook/buck2#264]
I have this rule:

```starlark
def _elm_test_impl(ctx: "context") -> [[DefaultInfo.type, ExternalRunnerTestInfo.type]]:
    command = [
        "elm-test", # TODO put in toolchain or params
        cmd_args(ctx.attrs._elm_toolchain.get(ElmToolchainInfo).elm, format="--compiler={}"),
        cmd_args(str(ctx.attrs.fuzz), format="--fuzz={}"),
    ]

    if ctx.attrs.seed:
        command.append(cmd_args(ctx.attrs.seed, format="--seed={}"))

    command.extend(ctx.attrs.test_srcs)

    return [
        DefaultInfo(),
        ExternalRunnerTestInfo(
            type = "elm_test",
            command = command,
            run_from_project_root = False,
        ),
    ]

elm_test = rule(
    impl = _elm_test_impl,
    attrs = {
        "test_srcs": attrs.list(attrs.source()),
        "fuzz": attrs.int(default=100),
        "seed": attrs.option(attrs.string(), default=None),
        "_elm_toolchain": attrs.toolchain_dep(
            default = "toolchains//:elm",
            providers = [ElmToolchainInfo],
        )
    },
)
```

When I define some non-project-root target with this rule (in this case available at `//component-catalog:elm_test`) the executor runs from the project root still, despite having `run_from_project_root = False`.

I have some memory that an earlier version of buck2 would change working directory for tests, and the docs seem to suggest that will happen too. Is that right or have I misunderstood something?

Version:

```
buck2 f8ff2901f86e397cb82f2052815889d3 <local>
```

**Comment by krallin** [comment]
Is it possible that you're confusing cells and packages here? The target name you're sharing *doesn't* have a cell, so that leads me to suspect you may not be using cells at all, in which case project root and cell root are the same thing.

To be very clear,  `component-catalog` is *not* a cell, it's a package.

**Comment by BrianHicks** [comment]
mmhmm! Ok then, so is there a way to get this to change directory? I thought it was working when I did an earlier prototype but similar code is not working now. 🤔

**Comment by krallin** [comment]
> Ok then, so is there a way to get this to change directory

You can't run tests from their package, no

**Comment by BrianHicks** [comment]
Ok. Just out of curiosity, why is that? It’s the same for build scripts and it’s meant doing a lot of extra work in Elm scripts specifically because the compiler assumes you’re running from the package root.On May 19, 2023, at 6:36 AM, Thomas Orozco ***@***.***> wrote:﻿

Ok then, so is there a way to get this to change directory

You can't run tests from their package, no

**Comment by krallin** [comment]
> Just out of curiosity, why is that?

I think the answer is primarily "because it's not implemented", but generally I think we try to avoid having too many ways of doing things. Running from the cell root was a concession because that's how Buck1 works, but all the actions Buck2 executes run from the project root.

We should probably make running from the project root & using relative paths the default in the OSS build.

> It’s the same for build scripts and it’s meant doing a lot of extra work in Elm scripts specifically because the compiler assumes you’re running from the package root

I'm really sorry, but i have no idea what you mean here

**Comment by BrianHicks** [comment]
Well, you said that `component-catalog` is a package, right? It happens to be an Elm app. The Elm compiler must be run from the directory containing its config file (`elm.json`.) Because of that, I have a Python script that takes all the arguments for the compiler and then changes directory and does a little more setup just before execution. It looks like it’ll be the same for the test script because of the same issue!

**Comment by krallin** [comment]
Right, I think the immediate answer here is that we've not needed that and it's pretty easy to workaround, so we never added it.

(I don't feel super strongly about whether or not that should exist, personally)
