### ISSUE TITLE
Build fails: no method named `process_group`

### ISSUE THREAD

**Issue by TheButlah** [facebook/buck2#275]
Machine: Apple M2 Pro, MacOS v13.3.1

Error:
```
error[E0599]: no method named `process_group` found for struct `tokio::process::Command` in the current scope
   --> app/buck2_client_ctx/src/subscribers/event_log/write.rs:371:17
    |
371 | ...   command.process_group(0); // @oss-disable: for some reason the ...
    |               ^^^^^^^^^^^^^ method not found in `Command`

   Compiling buck2_server_ctx v0.1.0 (/Users/ryan.butler/.cargo/git/checkouts/buck2-881d6af740402932/18ceb81/app/buck2_server_ctx)
For more information about this error, try `rustc --explain E0599`.
error: could not compile `buck2_client_ctx` due to previous error
```
[dump.txt](https://github.com/facebook/buck2/files/11560345/dump.txt)

**Comment by toothbrush7777777** [comment]
https://github.com/facebook/buck2/blob/e011a968d249d93b45f65974041241f8c9ec0b0d/app/buck2_client_ctx/src/subscribers/event_log/write.rs#L373

Note that line 373 has a comment with `@oss-disable` describing this exact issue but is not commented out in the OSS version.

This `@oss-disable` comment was added in [commit c3f145cc39941eb41149227c9c8287840b3cac3b (diff. rev. D46020659)](https://github.com/facebook/buck2/commit/c3f145cc39941eb41149227c9c8287840b3cac3b) but does not fix the issue.
