### ISSUE TITLE
Hard coded -fuse-ld=lld breaks gcc toolchain

### ISSUE THREAD

**Issue by jhdub23** [facebook/buck2#277]
I'm just starting to experiment with Buck2 and going through the [Creating your first hello_world project](https://buck2.build/docs/getting_started/#creating-your-first-hello_world-project) example, trying to use gcc instead of clang since we don't have clang installed on our systems.  I found #172 and added the following to the build file:

``` text
system_cxx_toolchain(
    name = "cxx",
    compiler_type = "gcc",
    compiler = "gcc",
    cxx_compiler = "g++",
    linker = "g++",
    cxx_flags = ["-std=c++20", "-O3"],
    visibility = ["PUBLIC"],
)
```

Compilation gave me an error:

```
Action failed: root//:main (cxx_link_executable)
Local command returned non-zero exit code 1
Reproduce locally: `g++ "-fuse-ld=lld" -o buck-out/v2/gen/root/524f8da68ea2a374/__main__/main @buck-out/v2/gen/root/524f8da68ea2a374/__main__/main.linker.argsfile`
stdout:
stderr:
collect2: fatal error: cannot find ‘ld’
compilation terminated.
```

I found the `-fuse-ld=lld` hard coded in `prelude/toolchains/cxx.bzl`.  Compilation succeeds if I comment out the hard-coded fuse dependency as follows (last two lines):

``` python
def _system_cxx_toolchain_impl(ctx):
    """
    A very simple toolchain that is hardcoded to the current environment.
    """
    ...
    if host_info().os.is_macos:
        linker_type = "darwin"
    elif host_info().os.is_windows:
       ...
    #else:
    #    additional_linker_flags = ["-fuse-ld=lld"]

```

Does anyone have any suggestions on the best way to handle this?

**Comment by dmoody256** [comment]
I copied the `cxx.bzl` toolchain file from prelude/toolchains to my own toolchains file, and then was able to customize it exactly how I wanted, and just renamed them to my own rule and impl function. Only took a few minutes to setup and works great.

**Comment by jhdub23** [comment]
Would it be possible to have gcc support out-of-the-box with some easy setting?  I'd propose a PR myself, but I don't know enough about Buck2 to suggest a code change.  I've never used Bazel or Buck, so I'm starting from scratch in understanding Buck2.

**Comment by cjhopman** [comment]
> Would it be possible to have gcc support out-of-the-box with some easy setting?

Yeah, I think this would be good, I think we'd like setup to be fairly easy for different possible configurations, but just that nobody has implemented it yet.

**Comment by wendy728** [comment]
@jhdub23 The hello_world example toolchain should be compatible with both clang and gcc now.
