### ISSUE TITLE
Noise in stderr output

### ISSUE THREAD

**Issue by benbrittain** [facebook/buck2#282]
The open source test runner emits noise that is somewhat confusing and unrelated when running tests now.

This behavior seems to be introduced in  0f23272e83b600db16af0be599c5382cbfc8e2dd

Should something be filtering this out?

```
[----------] Global test environment tear-down
[==========] 9 tests from 1 test suite ran. (20728 ms total)
[  PASSED  ] 9 tests.

---- STDERR ----

Success {
    execution_kind: Local {
        digest: 3717414d07bf3af05fd72477183fa0fdf6d4195bada66f61f4156da03b5e657f:142,
 
        command: [
         < COMMAND HERE>
        ],
        env: {
            "GTEST_COLOR": "1",
            "GTEST_SHUFFLE": "1",
        },
    },
}
```

**Comment by benbrittain** [comment]
cc/ @themarwhal @stepancheg

**Comment by stepancheg** [comment]
Ouch. Added it yesterday was investigated tests we could not reproduce locally.

Our internal test executor does not show it when tests pass.

Let me think.

**Comment by benbrittain** [comment]
I think like in #271 the "right" answer might be making the open source test runner behave a bit more like the internal stuff. Should `app/buck2_test_runner` be also omitting stderr (and stdout?) when the test passes?  I'd expect that.

**Comment by stepancheg** [comment]
OK, I'll do it.

**Comment by stepancheg** [comment]
(Internal: D46531416)
