### ISSUE TITLE
CLI config option are non-functioning (or not-documented)

### ISSUE THREAD

**Issue by benbrittain** [facebook/buck2#294]
Based on some buck1 documentation, I'm trying to get mode files working for release builds.

Mode files didn't seem to work, so I started messing around with --config args, which also seem to not do anything.

I've tried a few variants, none of them seem to be doing what I'd expect:

buck2 build --config='cxx.cxx_flags=oh no' //path/to/cxx:lib
buck2 build -c 'cxx.cxx_flags=oh no' //path/to/cxx:lib

Am I holding this wrong? What is the right way of doing release builds for c++?

I debug printf'd the argv that buck sees, and it looks like this: (when I was trying cpp_flags)

```
$ buck2 build //path/to/cxx:lib @//test.bcfg
Argv {
    argv: [
        "buck2",
        "build",
        "//path/to/cxx:lib",
        "@//test.bcfg",
    ],
    expanded_argv: [
        "buck2",
        "build",
         "//path/to/cxx:lib",
         "-c cxx.cppflags=-D_OH_ENTHU=\\\"DISABLED\\\"",
    ],
}
```

**Comment by benbrittain** [comment]
Is the right way to define a different platform type? like a release_clang vs a debug_clang?

**Comment by stepancheg** [comment]
> Is the right way to define a different platform type?

The official right way is to use `--target-platforms=` flag, but it is hard to use. `-c` and `read_config` is the second best option.

`-c` (or `--config`) just sets "buckconfig" (the same as specified in `.buckfonfig` or in your `.bcfg` file). These are accessed with `read_config` function. The easiest (and deprecated) way to access it is to specify in `BUCK` file:

```
my_flags = native.read_config("foo", "bar")

cxx_library(
  name = "xx",
  cxxflags = ["-D" + my_flags],
)
```

You probably want to specify `-O2` to all targets. I don't know how to do that officially, but I think it can be done by passing `cxxflags` to cxx toolchain rule here https://github.com/facebook/buck2/blob/27ec55b162ed6f8ef94a59cacfde19349e4567ea/examples/prelude/toolchains/BUCK#L7-L10

Most correct way is to define configurations with `platform()` rule, and use `select()` function to map constraints to flags. This is not very easy to use. However, now we are now working on ergonomic user interface to configurations: [RFC](https://github.com/facebook/buck2/blob/main/docs/rfcs/drafts/cfg-modifiers/api.md).

FYI "mode files" are just command line arguments in a file.

**Comment by benbrittain** [comment]
```
    cxx_flags = select({                                                                                                 
        "root//build/platforms:prod": [ "-O3" ],                                                                         
        "root//build/platforms:debug": [ "-O1" ],                                                                        
    }) + ["-std=c++17"],                                                                                                 
    link_flags = [    
```

Can confirm that a toolchain config works nicely :+1:
