### ISSUE TITLE
Hello, world example can't compile on Windows

### ISSUE THREAD

**Issue by zjturner** [facebook/buck2#295]
I tried to get the hello, world example building on Windows.  There seem to be a couple of issues.  But first, here's the error:

```
D:\src\buck2\examples\hello_world>buck2 build //:print --show-output
Action failed: root//:print (cxx_link lib_print.so)
Local command returned non-zero exit code 1
Reproduce locally: `"buck-out\\v2\\gen\\toolchains\\fb50fd37ce946800-fb50fd37ce946800\\__cxx__\\windows_linker.bat" /Bre ...<omitted>... \lib_print.so" "@buck-out\\v2\\gen\\root\\fb50fd37ce946800\\__print__\\lib_print.so.linker.argsfile" (run `buck2 log what-failed` to get the full command)`
stdout:
PATH = C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Program Files\Python310\Scripts\;C:\Program Files\Python310\;C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\Rust\bin;C:\Program Files\GitHub CLI\;C:\Program Files\Graphviz\bin;C:\Program Files\PowerShell\7\;C:\Users\Zachary Turner\.cargo\bin;D:\tools;C:\Program Files\LLVM\bin;C:\Users\Zachary Turner\.local\bin;C:\Users\Zachary Turner\AppData\Local\Microsoft\WindowsApps;C:\Users\Zachary Turner\.dotnet\tools;C:\Program Files\RedHat\Podman;C:\Users\Zachary Turner\AppData\Local\Programs\Microsoft VS Code\bin;
Running ['link.exe', '@D:\\src\\buck2\\examples\\hello_world\\buck-out\\v2\\tmp\\root\\fb50fd37ce946800\\__print__\\cxx_link\\lib_print.so\\tmp2_vc1_92']
stderr:
linker_args = [
    "/Brepro"
    "/OUT:buck-out\v2\gen\root\fb50fd37ce946800\__print__\lib_print.so"
    "/DLL"
    "buck-out\v2\gen\root\fb50fd37ce946800\__print__\__objects__\library.cpp.pic.o"
    "buck-out\v2\gen\root\fb50fd37ce946800\__print__\__objects__\main.cpp.pic.o"
    "/IMPLIB:buck-out\v2\gen\root\fb50fd37ce946800\__print__\lib_print.so.imp.lib"
]
Traceback (most recent call last):
  File "D:\src\buck2\examples\hello_world\buck-out\v2\gen\prelude\fb50fd37ce946800\cxx\tools\__linker_wrapper__\linker_wrapper.py", line 96, in <module>
    main()
  File "D:\src\buck2\examples\hello_world\buck-out\v2\gen\prelude\fb50fd37ce946800\cxx\tools\__linker_wrapper__\linker_wrapper.py", line 92, in main
    subprocess.run(command, check=True)
  File "C:\Program Files\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Build ID: b19321b9-5447-41ca-a1d7-5f99650bd9bf
Jobs completed: 3. Time elapsed: 0.0s. Cache hits: 0%. Commands: 1 (cached: 0, remote: 0, local: 1)
BUILD FAILED
Failed to build 'root//:print (prelude//platforms:default#fb50fd37ce946800)'
```

The `PATH=` and `Running ...` lines are lines I added into the Python script for debugging purposes.

Issue 1: link.exe and cl.exe expect to be run from a Visual Studio Command Prompt.  They rely on environment variables set, such as PATH, and INCLUDE and LIB.  But whatever this script is isn't respecting that.  We can see it in my printing of `PATH`, where you don't see any of the MSVC environment variables anywhere in the PATH.  So naturally `link.exe` cannot be found.  I'm doing this from a VS Command Prompt though, so it appears that buck2 is removing these environment variables from PATH.

Issue 2: It's calling clang++ for the compiler, even though this is Windows.  Shouldn't it be calling cl.exe?  I happen to have LLVM installed, so the compilation part is working, but then when it comes time to link it decides to use link.exe instead?

Issue 3: It seems to want to give libraries and objects the extension `.so` and `.o` instead of `.dll` and `.obj` (I'm actually not sure why there would be a dll involved here at all, I would expect libprint to be static)

What is the expected workflow when using Windows MSVC?  Should I be doing this from a VS Command Prompt?  If so, the bug seems to be that buck2 is not preserving the environment.  If not, how should I be telling it where to find my toolchain binaries?

If I wanted to try fixing some of these issues, where would be a good place to get my feet wet in looking at the code and applying fixes in the right place?

I asked a similar question about Windows a few months ago, but I was under the impression that MSVC toolchain support had been improved since then.

**Comment by ndmitchell** [comment]
Thanks for the report! We've made this work in https://github.com/facebook/buck2/commit/c483e5faffa97ddbbed80e3a815fb80002e3f686 and are hoping to add a CI test shortly as well to ensure it never regresses.

As to the aspects around MSVC, I'll find someone else to answer

**Comment by KapJI** [comment]
You don't have to run it form VS Command Prompt, but you need to have Visual Studio and Windows SDK installed. And `link.exe` location from MSVC needs to be added on `%PATH%`. Then Buck2 should find all necessary paths itself. It might be still incomplete, e.g. it doesn't add `/INCLUDE` paths explicitly, it seems compiler finds them automatically. But we may need to revisit this later. Create new issue if something is still missing there.

Currently system toolchain uses LLVM, so you need to have LLVM installed and added to `%PATH%` as well. But I'm planning to switch compiler to `cl.exe`, so it only uses MSVC.
