### ISSUE TITLE
How do you support unicorn source files?

### ISSUE THREAD

**Issue by zjturner** [facebook/buck2#317]
Suppose have a `cxx_library()` with 5 files.  Generally speaking, they all have the same command line options but you have one source file that needs a "unicorn" option.  `-ffast-math` is a good example of this, you might be building a math library where one file needs to be compiled with `-ffast-math`.  

Splitting it into a separate library is not going to be an option for us, because the cpp files have mutually interdependent headers.  For example, `A.cpp` includes `B.h` and `B.cpp` includes `A.h`.

Is there presently a way to accomplish something like this?

**Comment by cjhopman** [comment]
> Splitting it into a separate library is not going to be an option for us, because the cpp files have mutually interdependent headers. For example, A.cpp includes B.h and B.cpp includes A.h.

That shouldn't stop you from being able to split them as you could split them into three parts: a headers target, a B.cpp target and an A.cpp target, both of them depending on the headers, pick one to represent the whole thing and have it export the headers and depend on the other.

Anyway though, there's no need for that. you can do:

```
cxx_library(
  name = "x",
  srcs = [
    "a.cpp",
    "b.cpp",
    ("c.cpp", ["--flag-for-c-1", "--flag-for-c-2"]),
     "d.cpp",
  ],
  ...
)
```

It's documented here: https://buck2.build/docs/api/rules/#cxx_library:~:text=2.3%20on%20Linux.-,srcs%3A,-The%20set%20of

**Comment by zjturner** [comment]
Oh, that's interesting!  I didn't realize that srcs could be a list of tuples
