### ISSUE TITLE
Path to `bash` is hardcoded in many places

### ISSUE THREAD

**Issue by cbarrete** [facebook/buck2#319]
Some systems (such as NixOS) don't have a `/bin/bash`, or users might use a different `bash` than the system one (e.g. to get a more up-to-date version).
Replacing the occurences of `/bin/bash` by `/usr/bin/env bash` would enable those use-cases (another solution would be to use `/bin/sh` - which is portable - but of course that would be quite wildly breaking).

Would this be considered acceptable?

Thanks!

**Comment by stepancheg** [comment]
> Replacing the occurences of /bin/bash by /usr/bin/env bash

Sounds good.
