### ISSUE TITLE
Duplicated compiler options when using prebuilt_cxx_library

### ISSUE THREAD

**Issue by zjturner** [facebook/buck2#328]
Consider this small sample:

```
prebuilt_cxx_library(
    name = "config",
    exported_preprocessor_flags = [
        "-DFOO"
    ]
)

cxx_binary(
    name = "main",
    srcs = [
        "main.cpp"
    ],
    deps = [
        "//:config"
    ]
)
```

If you cat out the args file for `main.cpp`, you'll get something like this (ignore the windows specific options, I'm using a custom windows toolchain:

```
/std:c++17
/Zc:__cplusplus
/DNOMINMAX
"/D_WIN32_WINNT=0x0601"
"/D_SECURE_SCL=0"
"/DWINVER=0x0601"
"/DNTDDI_VERSION=0x06010000"
/DWIN32_LEAN_AND_MEAN
/Ideps/msvc-hermetic/msvc/include
"/Ideps/msvc-hermetic/msvc/atlmfc\\include"
/Ideps/winsdk-hermetic/winsdk/Include/shared
/Ideps/winsdk-hermetic/winsdk/Include/ucrt
/Ideps/winsdk-hermetic/winsdk/Include/um
/Brepro
-DFOO
-DFOO
/experimental:external
/nologo
```

Notice that `-DFOO` is duplicated.  I tried debugging the prelude with print statements, but I found it difficult to figure out where this is coming from.

I tried editing the function `cxx_merge_cpreprocessors` to print out the value and I get something like this:

```
CPreprocessorInfo(
	set=CPreprocessorTSet(
		value=[
			record(
				relative_args=record(args=["-DFOO"], file_prefix_args=[]), 
				absolute_args=record(args=[], file_prefix_args=[]), 
				headers=[], 
				raw_headers=[], 
				include_dirs=[], 
				system_include_dirs=record(compiler_type="windows", include_dirs=[]), 
				uses_modules=False, 
				modular_args=[], 
				modulemap_path=None
			), 
			record(
				relative_args=record(args=["-DFOO"], file_prefix_args=[]), 
				absolute_args=record(args=[], file_prefix_args=[]), 
				headers=[], 
				raw_headers=[], 
				include_dirs=[], 
				system_include_dirs=None, 
				uses_modules=False, 
				modular_args=[], 
				modulemap_path=None
			)
		], 
		0 children
	)
)
```

Which does have two separate records with this value.  But I'm still not sure how all of this fits together so maybe this is a red herring.  I know the error is mostly benign as duplicated command line options tend to be harmless, but it would be nice to see this fixed for command line cleanliness, and also because it could indicate some kind of deeper more subtle bug.

Happy to dig deeper if someone can offer pointers on where I should be looking.

**Comment by ndmitchell** [comment]
Thanks for the example! To get the output you can do `buck2 audit providers <my_target>` which will save you editing the code to see the preprocessor info. You can also do `buck2 build :main[compilation-database]` to get out the compilation database, which makes checking for duplicate fields much easier.

As far as I can tell, you are 100% right. I think changing https://github.com/facebook/buck2/blob/134ba2150318193ff7d2c2f26d65adee91aa8a3d/prelude/cxx/cxx.bzl#L320C13-L320C13 from:

```
args = cxx_attr_exported_preprocessor_flags(ctx)
```

To:

```
args = []
```

Fixes the issue. I'm just running that through our CI to be sure.

**Comment by zjturner** [comment]
Yea that fixes it for me.  I was actually looking at the exact same line locally, but I thought maybe the bug was inside the `cxx_merge_cpreprocessors` function and it was supposed to be merging across records.  I don't know enough to say one way or the other whether that would be correct or not.

**Comment by ndmitchell** [comment]
I'm not sure I know enough one way or the other - but being in both is definitely wrong, and getting it out of the second set of flags was much easier. I'll get someone more familiar with the code than me to review.

**Comment by ndmitchell** [comment]
Fixed in https://github.com/facebook/buck2/commit/3b55bf4749956da2d2a7c11e7e7ffbd4c919b8c8 - thanks for spotting and reporting it!
