### ISSUE TITLE
Feature: `buck2 init` should allow non-git-submodule initialization (and updates?)

### ISSUE THREAD

**Issue by thoughtpolice** [facebook/buck2#331]
Git submodules are not great. I avoid them at all costs in all places unless there is absolutely &mdash; and I mean *absolutely* &mdash; no alternative. I could go into this, but I'm going to assume there isn't enough space on the server hosting GitHub comments to handle it. The margins are too small, as a famous mathematician once said. Even if it could handle it, there are people not using git! For example this isn't going to work well with either [Sapling] or [Jujutsu] repositories, and I use both of them, with buck2.

[Sapling]: https://sapling-scm.com
[Jujutsu]: https://github.com/martinvonz/jj

So what I'd like to do is have the ability to download the prelude into a spot in my `$CWD` that I specify, just with a tarball. Yes, I realize this can be done with a call to `curl` in some sense. But why bother? It's also about user impressions and just making things nice and understanding that they won't always want that.

Also, there should be a way to update that copy too, I believe. This is also, IMO, just a nice bit of polish that users like. See the very end for that.

---

A basic proposal outline:

Make it so `buck2 init` has some slightly different semantics:

```bash
buck2 init --mode git --path buck2-prelude
buck2 init --mode raw --path buck2-prelude
```

So you specify a `--mode`, and a `--path`. You **must** specify `--mode` IMO, but we can have `--path` default to `buck2-prelude` in the current directory which is basically what it does now. An important distinction here from the current behavior with `--path` is that **the user gives the name of the folder to put the prelude, not the directory to put a `buck2-prelude` folder in**. This lets you change the name freely; for example I prefer to put everything buck related under `buck/`, so I personally might use the following command in my projects:

```bash
buck2 init -m raw -p buck/prelude # short for `--mode raw --path buck/prelude`
```

- **Q**: Why always specify a `--mode`?
  - **A**: Because implicitly choosing one is *not* a good idea IMO; this is a rare command, being fully explicit is OK (and I actually think doing something like getting clever about detecting `.git` and silently choosing one or the other isn't very nice, in contrast.)

- **Q**: The current semantics use `buck2 init ... -- <PATH>`. Why change this to use a `--path` flag?
  - **A**: Because the `init` command really takes *two inputs* in this new design, not one. Actually it always took two inputs, so in my opinion this is just correcting a UX irregularity. It's more "symmetric".

    While working on and with Jujutsu and Sapling, I really began to appreciate that certain commands that take multiple inputs always require actual flags to be given if you don't want the defaults. For example `jj rebase -s ... -d ...` which is a rebase; it's fundamentally a command with two inputs; neither is "more important" than another, and so they are both given flags. This means you also don't have to remember positional argument semantics (e.g. `buck2 init git path/to/folder`.) Yes, you can sometimes leave one flag out so it defaults to something. But if you have to give two inputs, they should have "symmetry" to the way you input them.

---

Technical algorithm:

- When given `--mode raw`, go check https://github.com/facebook/buck2-prelude and get the hash of the latest `HEAD`
  - In bash, something like `curl -sq https://api.github.com/repos/facebook/buck2-prelude/commits/main | jq -r '.sha'`
- Download a `.tar.gz` file of that has from an absolute URL on GitHub
- Untar the files from the prelude, and put the root of the directory at the place given by `--path`
  - There are cross platform tarball libraries here so this shouldn't be an issue with needing coreutils, cross platform compatibility, etc.
- Kick back, relax, and emit a big happy "Success" message and tell the user to enjoy using Buck2.

---

Side note: updating your copy of the prelude

If we're going to do this I think we should *also* maybe consider if we want to give the ability to *update* the prelude for the user too on their behalf. This is actually easier from a UX point of view because we can actually just look at the `.buckconfig` file to locate the `prelude//` cell! No real knobs needed, I think.

I believe this would be nice but it's actually trickier than the above scenario in some ways, and requires more UX work. For example I don't think it makes sense to have the `buck2 init` command do this, so maybe this should all be unified under a new `buck2 prelude` command:

```bash
buck2 prelude init --mode raw --path buck/prelude
# several hours later after a bugfix goes upstream
buck2 prelude update # implicitly knows the path is `buck/prelude`
```

What if it's a git submodule? Well, I think maybe we should just tell the user what commands to run, or that they should do it themselves in a high-level way; running those commands silently might not be advisable based on the state of the working copy. But we should hash that out if we get to it, I guess. I'm leaving the details here a bit "lighter" to see if there's interest in the original idea anyway.

**Comment by ndmitchell** [comment]
I think we probably want something more advanced than this - akin to Bazel's WORKSPACE or packages - but we aren't really sure what. Maybe the HTTP download capabilities and anon targets or dynamic outputs mean we can leverage those features somehow? But once we have a design for that space, I think it would be obvious if we need a dedicated mechanism for prelude, or it can reuse the generic mechanism. The git submodule was considered to be super cheap (basically write nothing) and work well enough to get started. We appreciate they have a lot of negative aspects, so it was only intended to be temporary.

**Comment by thoughtpolice** [comment]
This is basically now fixed by @JakobDegen's work on external cells. New users don't need to use git submodules and in fact dont' need to commit anything at all if the upstream prelude works OOTB for them!
