### ISSUE TITLE
Release a x86_64-unknown-linux-musl binary build

### ISSUE THREAD

**Issue by thoughtpolice** [facebook/buck2#341]
Thank you for the releases! I see a note in `upload_buck2.yml`: https://github.com/facebook/buck2/blob/a4e07fdf312e2669d01d9491e394beebdee76d0e/.github/workflows/upload_buck2.yml#L45-L46

It says it's broken, but it isn't clear how. This is just an issue to track that and fix it, since a lot of people will probably want a `musl` build if possible.

**Comment by themarwhal** [comment]
It is enabled now. Thanks for filing the issue!
