### ISSUE TITLE
How to write a macro that can process a selector?

### ISSUE THREAD

**Issue by zjturner** [facebook/buck2#347]
I'm trying to write a wrapper over `cxx_library()`, and I want to be able to pre-process the `deps` argument, for example by taking something like this:

```
deps = ["//foo:foo", "//bar:bar"] + 
    select({
        "DEFAULT": [].
        "config//os:windows": ["//baz:baz"]
    })
```

and applying a function to the each of the values `//foo:foo`, `//bar:bar`, and `//baz:baz` before forwarding it to the real `cxx_library()`.

When I do this I get an error:

```
Caused by:
    0: Error evaluating build file: `root//MyLib:BUCK`
    1: Traceback (most recent call last):
         * MyLib/BUCK:61, in <module>
             my_cxx_library(
         * my-prelude/my_cxx_library.bzl:59, in my_cxx_library
             spec_deps = _convert_deps(spec.value, deps)
       error: Operation `(iter)` not supported on type `selector`
         --> my-prelude/my_cxx_library.bzl:29:5
```

Is there any way of handling this?

**Comment by stepancheg** [comment]
There are functions like [select_map](https://buck2.build/docs/api/build/globals/#select_map) to process selects. But general idea is macros should not process selects, only append something to them. Rules should process arguments after selects are expanded. Maybe custom rules for the project.

**Comment by zjturner** [comment]
Thanks, this works.  In this case I think a rule is overkill.  I'm trying to write a macro to generate multiple variants of a cxx_library, with each variant having its own name.  Like `<lib-name>@variant`.  Deps that are specified should also link against the variant specific deps, so if `foo` links against `bar`, then `foo@v1` should link against `bar@v1` while `foo@v2` should link against `bar@v2`.  But this should all be hidden away from the user, and the user should just specify that `foo` links against `bar`.  

I think most of this is unnecessary with the configuration RFC that I've seen, but I'm just exploring this alternative for the time being.  But I got it working with `select_map()`, so i'll close this out.  Thanks!

**Comment by stepancheg** [comment]
Possible alternative is to make the library an alias:

```
cxx_library(
  name = "lib-variant1",
)

cxx_library(
  name = "lib-variant2",
)

alias(
  name = "lib",
  deps = select({
    ":cond": ":lib-variant1",
    "DEFAULT": ":lib-variant2",
  }),
)
```

so no need to rewrite deps.
