### ISSUE TITLE
How would you select on compiler?

### ISSUE THREAD

**Issue by zjturner** [facebook/buck2#350]
I am writing my own hermetic toolchains for all platforms (linux, windows, mac, mobile).  The host os is independent of the compiler.  For example, on Windows can we use MSVC, clang-cl, or clang windows.  On Linux we can use gcc or clang.  And Mac we have Apple Clang, which has subtly different options, but in theory one could use upstream LLVM clang on Apple.

But the definition of the toolchain file obviously knows what toolchain it is, and I'd like a way to have that code define some of constraint setting so that elsewhere in the code (for example when defining the flags for a certain `cxx_library()`, I can `select()` on the compiler flavor.

What's the best way to do this?  I feel like I need something like this:

```
constraint_setting(
    name = "compiler",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "msvc",
    constraint_setting = ":compiler",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "clang",
    constraint_setting = ":compiler",
    visibility = ["PUBLIC"],
)
```

But I don't know how to set the value of this setting from toolchain.  It looks like the list of constraints are intended to be set at the very beginning by constructing a `PlatformInfo()`.  My toolchain impl (which is where the decision about which compiler to use is made) looks roughly like this currently:

```
load("win_msvc.bzl", "my_msvc_toolchain_impl")
load("macos_clang.bzl", "my_macos_clang_toolchain_impl")

def _my_cxx_toolchain_impl(ctx):
    if host_info().os.is_windows:
        return my_msvc_toolchain_impl(ctx)
    elif host_info().os.is_macos:
        return my_clang_toolchain_impl(ctx)
    else:
        return []

my_cxx_toolchain = rule(
    impl = _my_cxx_toolchain_impl,
    attrs = {
        "linker_wrapper": attrs.default_only(attrs.dep(providers = [RunInfo], default = "prelude//cxx/tools:linker_wrapper")),
        "make_comp_db": attrs.default_only(attrs.dep(providers = [RunInfo], default = "prelude//cxx/tools:make_comp_db")),
    },
    is_toolchain_rule = True,
)
```

And this seems too far detached from the construction of the `PlatformInfo()` to pipe this information across the boundary that I need to pass it across.

To give a concrete use case for this, suppose we have a header only target `T`.  When building with Visual Studio 2019, it is warning free, but in VS 2022, a new warning was introduced into the compiler that triggers on this target.  We want to export the option to disable this warning to `T` and all targets that depend transitively on `T`.  But since this warning doesn't exist on VS 2019, we have to do this only when VS 2022 is actually in use.  In other words, if I were to do this:

```
cxx_library(
    name = "T",
    exported_preprocessor_flags=select({
        "DEFAULT": [],
        "config//os:windows": ["/wd3912"]
    })
```

Then if I'm using VS 2019, I will get an error "Warning 3912 is unrecognized".  But if I don't include that, then if I'm using VS 2022 the warning will trigger.

I could put this in the definition of the toolchain itself, when constructing the `CxxToolchainInfo`, and just pass it in via `compiler_flags` so that it's global.  But I don't want it to be global, because I might actually want to fix the warning elsewhere.  So it really needs to be selectable somehow.

This suggests to me that somehow I need to be able to have my toolchain define constraint settings, constraint values, and configuration settings that are queryable from other parts of the build.  And this is what I'm stuck on.

**Comment by zjturner** [comment]
Thanks.  I got all this working.  One question I have is why it’s not possible to specify multiple target platforms on the command line so that they build in parallel?

is this something that will be addressed by configuration modifiers?

to use the example of debug and release, there’s no fundamental reason I can think of why I shouldn’t be able to build debug and release in parallel, but this seems to not be possible using target platforms command line option

**Comment by stepancheg** [comment]
> why it’s not possible to specify multiple target platforms on the command line so that they build in parallel?

No reason, just did not implement it.

> is this something that will be addressed by configuration modifiers?

With configuration modifiers it will be possible.

**Comment by zjturner** [comment]
Awesome, looking forward to it!
