### ISSUE TITLE
Is there a timeline for adopting the configuration modifiers RFC?

### ISSUE THREAD

**Issue by zjturner** [facebook/buck2#351]
I was reading the [Configuration Modifiers RFC](https://github.com/facebook/buck2/blob/bb71fd0d006092ffaf0d7073c12249bc421e4ba5/docs/rfcs/drafts/cfg-modifiers/api.md) and it seems to solve exactly the current issue I'm having (and which is one of just a very few number of things blocking us from adopting buck2).  It looks like it's in Draft state though, so it isn't clear to me if this is still under discussion, or if it's approved, or if it's currently being worked on, or anything like that.

Can anyone comment on this?  When (if ever) might we be able to expect to see this work make it into mainline buck2?

**Comment by scottcao** [comment]
I'm planning on implementing it this half. We are in process of finalizing the design, which has already gone through a number of changes that haven't been reflected on the RFC yet, but the things it's trying to achieve are unchanged and largely agreed on.

**Comment by zjturner** [comment]
Thanks!
