### ISSUE TITLE
Is there a way to logically OR constraints together?

### ISSUE THREAD

**Issue by zjturner** [facebook/buck2#355]
It looks like `config_setting()` gives you a way to logically AND together `constraint_values`.  For example, if you do this:

```
config_setting(
    name = "clang_and_debug",
    constraint_values = [
        "test//constraints/compiler:clang",
        "test//constraints/config:debug"
    ],
    visibility = ["PUBLIC"],
)
```

you can then write:

```
select({
    "test//config:clang_and_debug": <result>
})
```

And the select will evaluate to <result> if both the clang and debug constraints are satisfied.  But I cannot find a way to achieve a logical or.  Is this possible?

**Comment by stepancheg** [comment]
No it is not possible.

A helper functions can help:

```
def select_or(key1, key2, value, default):
  return select({
    key1: value,
    key2: value,
    "DEFAULT": default,
  })
```

Alternatively, another constraint can be introduced which is included in both config settings, and select done on that constraint.

**Comment by zjturner** [comment]
Thanks!

**Comment by zjturner** [comment]
I think a helper function doesn't actually work, because it just gives you the error that multiple keys match, but neither is more specific.  I wonder if there could be an exception to the "more specific" rule implemented, such that as long as all values are identical, it doesn't matter if any is more specific.

**Comment by stepancheg** [comment]
OK, better version of the function which handles constraints which are not specific:

```
def select_or(key1, key2, value, default):
  return select({
    key1: value,
    "DEFAULT": select({
      key2: value,
      "DEFAULT": default,
    }),
  })

```

**Comment by zjturner** [comment]
Aha, that does work.  I guess I could make it recursive with a list of args too, to make it more generic.  Is this inefficient at evaluation time?  Do you think it's worth adding an exception to the non-specific rule when all values are identical?

**Comment by stepancheg** [comment]
> Is this inefficient at evaluation time?

Compared to other heavy work buck2 is doing, probably not. If "or" was supported natively, the amount of work would not be much smaller.

> Do you think it's worth adding an exception to the non-specific rule when all values are identical?

That would be too much magic and fragile.

For example, minor refactoring can break selects, for example:

```
select({
  ":a": [],
   ":b": [], # change to ["-DA"] and this selects breaks
})
```

(If by identity you mean equality; there's no notion of value identity in starlark language)

CC @cjhopman who thinks we should abandon this "more specific" rule, and evaluate keys in declaration order by either relying on dict being ordered or by inventing different syntax for select.

**Comment by zjturner** [comment]
Actually, maybe `select()` can just be taught to accept either a list or a dict, and the implementation can internally say "if it's a dict, do it this way.  If it's a list, do it the other way".

**Comment by stepancheg** [comment]
> Maybe it's difficult because it's a dictionary

This is one of the reasons.

Especially when select is generated by some complex code for example.

Or it can be accidentally reordered by incorrectly configured code formatters (or IDEs).

> I don't know if Starlark allows you to iterate a dictionary in declaration order,

It does. Iteration order is insertion order.

> Actually, maybe select() can just be taught to accept either a list or a dict, and the implementation can internally say "if it's a dict, do it this way. If it's a list, do it the other way".

Or a user can write a wrapper function which translates to nested selects which evaluate keys in the specified order.
