### ISSUE TITLE
How to select on a rule's impl

### ISSUE THREAD

**Issue by zjturner** [facebook/buck2#356]
I was trying to write a toolchain that would automatically select an appropriate compiler based on the host operating system.  It looks like this:

```

def _my_cxx_toolchain_impl(ctx):
    if host_info().os.is_windows:
        return my_msvc_toolchain_impl(ctx)
    elif host_info().os.is_macos:
        return my_apple_clang_toolchain_impl(ctx)
    else:
        return []

my_cxx_toolchain = rule(
    impl = _my_cxx_toolchain_impl,
    attrs = {
        "linker_wrapper": attrs.default_only(attrs.dep(providers = [RunInfo], default = "prelude//cxx/tools:linker_wrapper")),
        "make_comp_db": attrs.default_only(attrs.dep(providers = [RunInfo], default = "prelude//cxx/tools:make_comp_db")),
    },
    is_toolchain_rule = True,
)

my_cxx_toolchain(
    name="cxx",
    visibility=["PUBLIC"]
)
```

I tried to change it to this:

```
def _my_cxx_toolchain_impl(ctx):
    if host_info().os.is_windows:
        return my_msvc_toolchain_impl(ctx)
    elif host_info().os.is_macos:
        return my_apple_clang_toolchain_impl(ctx)
    else:
        return []

my_cxx_toolchain = rule(
    impl = select({
        "config//os:windows": my_msvc_toolchain_impl,
        "config//os:macos": my_apple_clang_toolchain_impl
    }),
    attrs = {
        "linker_wrapper": attrs.default_only(attrs.dep(providers = [RunInfo], default = "prelude//cxx/tools:linker_wrapper")),
        "make_comp_db": attrs.default_only(attrs.dep(providers = [RunInfo], default = "prelude//cxx/tools:make_comp_db")),
    },
    is_toolchain_rule = True,
)
```

But I get the following error `error: Operation call() not supported on type selector`.

I also tried defining all toolchains with `rule()` directly, and using `alias()`, e.g.

```
macos_clang_toolchain = rule(...)
windows_msvc_toolchain = rule(...)

alias(
    name = "cxx",
    actual_target = select({
        "config//os:windows": windows_msvc_toolchain,
        "config//os:macos": macos_clang_toolchain,
    })
)
```

But that gives me an error that `toolchains//:cxx` is not a toolchain rule.

What is the idiomatic way of doing this?

**Comment by cjhopman** [comment]
Try it with `toolchain_alias` instead of `alias`. The alias approach is what I would generally recommend here.

**Comment by cjhopman** [comment]
An edge between a normal rule and a toolchain rule is special, and it's a property of the rule type (the is_toolchain_rule=True in the rule() call) and the edge type (the dependent would have an attr.toolchain_dep()). alias is a normal rule, toolchain_alias is basically the same but is a toolchain_rule. If you want an alias for a toolchain rule (either because you just want another name for it, or, probably more commonly, because you want a select there), use toolchain_alias

**Comment by zjturner** [comment]
Hah, simple. That seems to be absent from the docs so I didn’t even think to try.  Thanks

**Comment by zjturner** [comment]
I’ll make a PR to update the docs tomorrow just to go through the flow, I already have a couple other functionality oriented PR ideas in mind anyway so I should probably start with something simple

**Comment by cjhopman** [comment]
Ah, it's not documented because it's not actually in the prelude. Here's the impl in the examples: https://github.com/facebook/buck2/blob/2563929ccbedcaa5d748872c3d2cd877f25ce1d0/examples/bootstrap/toolchains/toolchain.bzl#L19

**Comment by zjturner** [comment]
Ahh.  Is it worth putting in the prelude?  It seems pretty valuable.

if the answer is yes, maybe I can try making a PR to do that
