### ISSUE TITLE
Simple example of code generation with variable number of generated sources?

### ISSUE THREAD

**Issue by jgarvin** [facebook/buck2#361]
I'd like to have a target in buck2 that runs a python script, and then have the python script generate some number of `.cpp` files, but how many is unknown at the time I write the `BUCK` file and might be a function of the input file given to the python script (which itself may have been built by buck2 earlier). I then want to compile these files, potentially with non-default compile flags and dependencies. In other words, I need to somehow generate a dynamic number of `cc_library` calls and/or a single `cc_library` call with a dynamic number of sources (being able to do both would be ideal). Is that possible with buck2?

**Comment by cjhopman** [comment]
With the existing rules in the prelude, it's not possible. If you actually need multiple cxx_library targets, that's also not possible. What would be possible with your own cxx_library rule (or a lightly forked one) would be this:

A python script generates some unknown number of cpp files, each of which has its own custom flags (but mostly common) and a common set of dependencies that are some subset of a known previously declared possible set.

Given that cxx_librarys are consumed in a way that they propagate up information about themselves and their dependencies, I guess you could effectively have one that effectively acts as though it were a whole bunch (i.e. you could have every cpp file compile as its own shared lib and against different deps, including against other libs in that target).

In practice what has worked best is to not allow an unknown number of .cpp files to be generated, instead if you explicitly specify the list things become a lot easier.

**Comment by jgarvin** [comment]
Thanks, good to know
