### ISSUE TITLE
Documentation for local custom rules

### ISSUE THREAD

**Issue by cbarrete** [facebook/buck2#370]
Hi,

I would like to use buck2 in a project that uses a custom language (using a custom toolchain). My understanding is that, to get first class binary/test targets out of this, I will need to write custom rules (`genrule` can only get me so far).

I've read https://buck2.build/docs/rule_authors/writing_rules/, but it seems to be written with upstreaming to the prelude in mind, something that does not make sense in my case.

I've tried to follow the instructions in a local `BUCK` file, but `buck2` complains e.g. about the type annotations (error: type annotations are not allowed in this dialect), which I believe stems from this being in a `BUCK` file rather than a `.bzl` file. I've tried to split that out in a `.bzl` file and `load()` it, but no dice either.

Anyway, it's not really clear to me how to go about this and whether this is supported. If so, would it be possible to have some documentation about this?

Thanks a lot!

**Comment by krallin** [comment]
> I've tried to split that out in a .bzl file and load() it, but no dice eithe

You should be able to do that just fine. Can you share the code where it didn't work?

**Comment by cbarrete** [comment]
Well the loading part seems fine, but I suppose that I'm missing other loads. Here is a cut-down reproduction:

`my_lang.bzl`:
```
def my_lang_binary_impl(_ctx: AnalysisContext) -> ["provider"]:
    return [DefaultInfo()]
```

`BUCK`:
```
load("my_lang.bzl", "my_lang_binary_impl")
```

Then:
```
> buck2 build ...
From `load` at repro/BUCK:1:6-19

Caused by:
    0: Error evaluating module: `root//repro/my_lang.bzl`
    1: error: Variable `AnalysisContext` not found
        --> repro/my_lang.bzl:1:31
         |
       1 | def my_lang_binary_impl(_ctx: AnalysisContext) -> ["provider"]:
         |                               ^^^^^^^^^^^^^^^
         |

Build ID: 3ad5fc34-a936-472b-860b-4340a858be8a
Jobs completed: 3. Time elapsed: 0.0s.
BUILD FAILED
```
which isn't particularly surprising, but I don't know where to go from there (to be fair, I haven't spent more time on this since last time).

I expect that this is because I'm not doing step 2 of https://buck2.build/docs/rule_authors/writing_rules/, but it's specifically what I'm trying to avoid.

**Comment by cbarrete** [comment]
I've managed to make quite a bit of progress by following the [no prelude example](https://github.com/facebook/buck2/tree/main/examples/no_prelude), so I'll just close this issue.
