### ISSUE TITLE
buck2's MSVC support doesn't understand Visual Studio Build Tools installation

### ISSUE THREAD

**Issue by bruxisma** [facebook/buck2#377]
When running `buck2 build ://main` from a freshly initialized version of the `hello_world` example, I get the following error:

```console
$ buck2 build ://main
...
vswhere.exe did not find a suitable MSVC toolchain containing cl.exe, lib.exe, ml64.exe
```

However, upon running vswhere.exe manually, I get the following output:

```console
$ & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -nologo -products "*" -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64
... output omitted for brevity ...
installationName: VisualStudio/17.6.5+33829.357
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
installationVersion: 17.6.33829.357
productId: Microsoft.VisualStudio.Product.BuildTools
... output omitted for brevity ...
```

One will notice that I am passing `-products "*"` to vswhere, however [this is not done by buck2](https://github.com/facebook/buck2/blob/f0c32c8146a520c3273443a0b4a8ff847d58a3cb/prelude/toolchains/msvc/vswhere.py#L62), which means that a Build Tools only installation of Visual Studio will fail to be detected correctly even if the required component is correctly installed.

**Comment by KapJI** [comment]
I can fix this on Monday.

**Comment by dtolnay** [comment]
I inadvertently omitted that flag when I ported the vswhere logic from `cc` in 1fba8bc86a6695c127ce7434a4b3e4e5160253d4. `cc` passes `-products "*"` here: https://github.com/rust-lang/cc-rs/blob/1.0.81/src/windows_registry.rs#L344-L345 &mdash; makes sense to match in Buck2.
