### ISSUE TITLE
When do attrs.source() path dependencies get resolved?

### ISSUE THREAD

**Issue by dmzt99** [facebook/buck2#396]
I noticed that this kind of thing doesn't work:

```starlark
toolchain_that_might_exist_on_disk_depending_on_exec_host(
    name = "toolchain-macos",
    path = "/tools/toolchain-macos"  # an attrs.source()
)

toolchain_that_might_exist_on_disk_depending_on_exec_host(
    name = "toolchain-linux",
    path = "/tools/toolchain-linux"  # an attrs.source()
)

alias(
    name = "toolchain",
    actual = select({
        "prelude//os:macos": ":toolchain-macos",
        "prelude//os:linux": ":toolchain-linux"
    })
)
```

Because buck2 eagerly looks for the attrs.source() on the filesystem for both `:toolchain-macos` and `:toolchain-linux`, even when only one will actually be used.

Is this intentional behavior? It seems to make it impossible to configuration-conditionally use preexisting sources.

**Comment by krallin** [comment]
attrs.source() is for files (or directories) in the repository that will be
watched for changes, it’s not for arbitrary paths on the file system.

Given your use case, you probably want attrs.string() instead. This does
mean Buck will not monitor those files for changes, but if they are not
present on the local machine, there is no way for that to happen anyway.

That said, to answer your original question: sources are normally checked
for existence at loading time (when evaluating the BUCK file), and then
their actual contents are accessed when they’re used for an action.

**Comment by dmzt99** [comment]
Right, `attrs.string()` is how I've been solving this problem for local development, but this stops working with Remote Execution if I want the source to actually be sent to the remote executor. Maybe the answer here is that it must already exist in some absolute path on the executor. Is there a way I can express this kind of "optional" source?

**Comment by krallin** [comment]
In buck2, source files must be within the project, there’s not really any
getting around that.

You won’t be able to get Buck2 to upload something to remote execution that
is not within the project (except maybe by tricking buck2 into not noticing
this via e.g. the use of bind mounts).

If you’ve got some things you want to access that are outside the project,
you can do so and then use attrs.string (or attrs.source on a symlink
pointing outside the project), but you would need to ensure they’re in the
same location on your RE worked and on your local machine.

Most public RE providers allow you to select a custom docker image to run
your RE jobs in so you could leverage that to provide those external
dependencies.

**Comment by dmzt99** [comment]
@krallin That makes sense, thanks. I understand why .source() doesn't work this way, but I do wish there was a different, late-resolving version that would make this work, even if doing it for toolchains isn't necessarily the best idea. Thanks again!
