### ISSUE TITLE
Expand XAR acronym in docs

### ISSUE THREAD

**Issue by thetimmorland** [facebook/buck2#413]
Would it be possible to give the full name for "XAR" acronym in this section of the docs?: https://buck2.build/docs/developers/architecture/buck1_vs_buck2/#non-determinism

**Comment by ndmitchell** [comment]
I'll add a link to https://engineering.fb.com/2018/07/13/data-infrastructure/xars-a-more-efficient-open-source-system-for-self-contained-executables/ since the actual acronym is mostly useless.

**Comment by ndmitchell** [comment]
Fixed in 143d443a3739d34aad886fa7ea67f1dc2c8fe719
