### ISSUE TITLE
How to depend on libraries like zlib and llvm using Buck2?

### ISSUE THREAD

**Issue by dopamane** [facebook/buck2#414]
I am evaluating buck2 for use in a project. I have a C++ library which depends on zlib. Here is my attempt at getting the zlib dependency:

```
git_fetch(
  name = 'zlib_git',
  repo = 'https://github.com/madler/zlib',
  rev  = '09155eaa2f9270dc4ed1fa13e2b4b2613e6e4851',
)

genrule(
  name = 'libz_a',
  out = 'libz.a',
  cmd = 'cd zlib_git;\
         export CC=clang;\
         export CXX=clang++;\
         ./configure --static;\
         make;\
         cat libz.a > ${OUT}',
  srcs = [':zlib_git'],
  visibility = ['PUBLIC'],
)

prebuilt_cxx_library(
  name = 'zlib',
  static_lib = ':libz_a',
  visibility = ['PUBLIC'],
)
```

Then, my plan was to add the dependency to my library:

```
cxx_library(
  name = 'mylib',
  deps = [':zlib'],
)
```

But I keep getting errors on the `:libz_a` genrule like:
`line 5: ../out/libz.a: No such file or directory`
and
`Required outputs are missing: Action failed to produce outputs`

I've tried various things like `cp`, or `cat libz.a > ../${OUT}`, or changing `out = 'zlib_git/libz.a'` but no luck on getting any output. I can see the `libz.a` source file in the `srcs` directory too under `buck-out`, so `configure` and `make` are running fine. I also tried creating a `filegroup` with `srcs = ['/usr/lib/x86_64-linux-gnu/libz.a']` but buck2 can't access absolute paths. I already have zlib installed on my system using `apt install zlib1g-dev` so technically I don't see a reason to rebuild zlib from git but adding `linker_flags = [ '-lz' ]` doesn't work either. I've simplified this example and ignored the header files `zlib.h`, `zconf.h` but I will eventually need those too.

How can I depend on a library like zlib using buck2?

**Comment by krallin** [comment]
This happens because OUT is a relative path so after you cd it’s no longer
correct. You could update your genrule by taking an absolute path earlier
for OUT (using e.g. realpath), or avoid the cd.

Separately I think we’d also generally recommend vendoring and not using a
genrule to build your C libraries (instead using rules like cxx_library),
but that’s a separate discussion.

**Comment by dopamane** [comment]
Interesting. I've worked around the `cd` issue and I can build libz.a, and extract the headers:
```
git_fetch(
  name = 'zlib_git',
  repo = 'https://github.com/madler/zlib',
  rev  = '09155eaa2f9270dc4ed1fa13e2b4b2613e6e4851',
)

genrule(
  name = 'libz_a',
  out = 'libz.a',
  cmd = 'export CC=clang;\
         export CXX=clang++;\
         cp -r zlib_git/. .;\
         ./configure --static;\
         make;\
         cat libz.a > ${OUT}',
  srcs = [':zlib_git'],
  visibility = ['PUBLIC'],
)

genrule(
  name = 'zlib_h',
  out = 'zlib.h',
  cmd = 'cp -r zlib_git/. .;\
         cat zlib.h > ${OUT}',
  srcs = [':zlib_git'],
  visibility = ['PUBLIC'],
)

genrule(
  name = 'zconf_h',
  out = 'zconf.h',
  cmd = 'cp -r zlib_git/. .;\
         cat zconf.h > ${OUT}',
  srcs = [':zlib_git'],
  visibility = ['PUBLIC'],
)

prebuilt_cxx_library(
  name = 'zlib',
  static_lib = ':libz_a',
  exported_headers = [':zlib_h', ':zconf_h'],
  visibility = ['PUBLIC'],
)
```
However, when building `:zlib` I'm seeing errors:
```
Local command returned non-zero exit code 1
Reproduce locally: `env -- "BUCK_SCRATCH_PATH=buck-out/v2/tmp/root/524f8da68ea2a374/src/mylib/cpp/__zlib__/cxx_link" clang++ @buck-out/v2/gen/root/524f8da68ea2a374/src/mylib/cpp/__zlib__/libzlib.so.linker.argsfile`
stdout:
stderr:
ld.lld: error: can't create dynamic relocation R_X86_64_32 against local symbol in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in buck-out/v2/gen/root/524f8da68ea2a374/src/mylib/cpp/__libz_a__/out/libz.a(crc32.o)
>>> referenced by crc32.c
>>>               crc32.o:(get_crc_table) in archive buck-out/v2/gen/root/524f8da68ea2a374/src/mylib/cpp/__libz_a__/out/libz.a
```
I tried adding `linker_flags = ['-Wl,-z,notext']` to `prebuilt_cxx_library` but it still errors and says "Recompile with -fPIC".

I'm using a `genrule`, instead of vendoring with `cxx_library`, because in addition to zlib I also need to depend on LLVM libraries. I don't see how using `cxx_library` is a viable solution for building a dependency like LLVM which is large, changes often, and already has an intricate CMake build system. So my plan was to use genrules similar to zlib here to invoke CMake.
 
Open to suggestions.
