### ISSUE TITLE
Misnamed action in `anon_targets.md`

### ISSUE THREAD

**Issue by thetimmorland** [facebook/buck2#415]
I think `ctx.actions.promise_artifact()` should be `ctx.actions.artifact_promise()` here: https://github.com/facebook/buck2/blob/7c0c983940e2d5397af7c2d1e02eccd0f087d44d/docs/rule_authors/anon_targets.md?plain=1#L132

**Comment by ndmitchell** [comment]
Thanks! I've shoved up an internal diff to fix it, which should sync back here in a bit.

**Comment by wendy728** [comment]
We updated the promise artifact API. Docs are updated now
