### ISSUE TITLE
How to build Haskell binary?

### ISSUE THREAD

**Issue by dopamane** [facebook/buck2#429]
I am seeing an error when trying to build a [`haskell_binary`](https://buck2.build/docs/api/rules/#haskell_binary):
```
$ buck2 build //:foo
File changed: root//.BUCK.swp
File changed: root//.BUCK.swpx
File changed: root//4913
2 additional file change events
Error running analysis for `root//:foo (prelude//platforms:default#524f8da68ea2a374)`

Caused by:
    0: Error looking up configured node root//:foo (prelude//platforms:default#524f8da68ea2a374)
    1: Error looking up configured node toolchains//:haskell (prelude//platforms:default#524f8da68ea2a374) (prelude//platforms:default#524f8da68ea2a374)
    2: looking up unconfigured target node `toolchains//:haskell`
    3: Unknown target `haskell` from package `toolchains//`.
       Did you mean one of the 3 targets in toolchains//:BUCK?
Build ID: 44aa849e-66b8-43fa-b1f7-8eee6a252281
Jobs completed: 4. Time elapsed: 0.0s.
BUILD FAILED
```

My guess is I'm missing a Haskell toolchain. I setup the project with `buck2 init --git` and I see the `prelude/haskell/haskell.bzl` file but I don't see any `haskell` directory under `prelude/toolchains`. Am I looking in the wrong location? Is it not implemented yet?

`Main.hs`:
```haskell
main :: IO ()
main = putStrLn "Hello"
```
`BUCK`:
```
haskell_binary(
  name = 'foo',
  srcs = [
    'Main.hs',
  ],
)
```
`toolchains/BUCK`:
```
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)
system_cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)
system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)
```

**Comment by thoughtpolice** [comment]
No, there isn't a default toolchain for several languages yet. In short: by default, `toolchains//:haskell` needs to be a target that returns a `HaskellToolchainInfo`, describing how to invoke and run the compiler &mdash; much like how `system_cxx_toolchain` is a rule that returns a `CxxToolchainInfo` which describes how to run *that* compiler. Once that's done, then by default all those rules like `haskell_binary` will specify a (default, but overridable) dependency on `toolchains//:haskell` target, and that's the information they'll use to invoke the compiler correctly.

If you look at [./prelude/toolchains/cxx.bzl](https://github.com/facebook/buck2/blob/main/prelude/toolchains/cxx.bzl), you can see that it is basically a long function that in the end just returns a `CxxToolchainInfo`.

Honestly writing a default `system_haskell_toolchain` rule probably isn't that hard. You just need to return a reasonable set of default values for all the fields of `HaskellToolchainInfo`.

**Comment by thoughtpolice** [comment]
Unfortunately the Haskell rules currently aren't workable as they require a patched version of GHC 9.2, it seems. The below rule is *almost* enough, but leaves us at an insurmountable point:

```bazel
load("@prelude//haskell:haskell.bzl", "HaskellPlatformInfo", "HaskellToolchainInfo")

def _system_haskell_toolchain(ctx: AnalysisContext) -> list[Provider]:
    return [
        DefaultInfo(),
        HaskellToolchainInfo(
            compiler = ["ghc"],
            compiler_flags = [],
            linker_flags = [],
        ),
        HaskellPlatformInfo(
            name = "x86_64",
        )
    ]

system_haskell_toolchain = rule(
    impl = _system_haskell_toolchain,
    attrs = {
    },
    is_toolchain_rule = True,
)
```

You could use this rule to implement the `toolchains//:haskell` target, I think, but then you get this:

```
Local command returned non-zero exit code 1
Reproduce locally: `env -- "BUCK_SCRATCH_PATH=buck-out/v2/tmp/tilde/dd49f9db9d4e177e/aseipp/hs/__hello__/haskell_compile_shared" ghc @buck-out/v2/gen/tilde/dd49f9db9d4e177e/aseipp/hs/__hello__/haskell_compile_shared.argsfile`
stdout:
stderr:
ghc-9.6.2: unrecognised flag: -expose-package
did you mean one of:
  -ignore-package

Usage: For basic information, try the `--help' option.
Build ID: 5ae0821c-6a63-4921-b59d-3cf8ae912afd
Jobs completed: 50. Time elapsed: 0.1s.
Cache hits: 0%. Commands: 1 (cached: 0, remote: 0, local: 1)
BUILD FAILED
```

Some sleuthing in the GHC repository shows that this flag is from an out-of-tree patch (that seemed to initially have been authored on Phabricator, sure enough, but as of sometime last year was put on a branch named `wip/ghc-9.2-fb-linker`): https://github.com/ghc/ghc/commit/911b97008e1eab24003655a6381373ab9c46a2a5

So, I think there will still be some time yet before upstream GHC support is workable, I guess, unless I or someone else dug into it...

**Comment by dopamane** [comment]
Thanks for the debug, looking forward to seeing Haskell support in the future. buck2 has a lot of potential!

**Comment by ndmitchell** [comment]
There are two paths forward:

1. Maybe we don't need to ever use `expose-package` and merely `package` is sufficient. I tested a diff that made that change internally and no tests failed. That means either our tests are insufficient, or it's not required. Will follow up on that next week.
2. Maybe we do need `expose-package`, but it should be a setting on the toolchain, which defaults the right way in open source.

It will have to wait til next week to figure that out when the authors of these bits are back online.

**Comment by ndmitchell** [comment]
I fixed the expose-package in bee7d591e9537b510b10d0ff798382724f75d35a. There is also a system_toolchain in 93f1008dfa671d7810220544a4f883e17b07a212. I haven't been able to test this end to end internally, but it might work.

**Comment by thoughtpolice** [comment]
Looks like #445 was merged and there are now working Haskell examples in the prelude! So those fixes should happen with the upcoming 10-30-2023 release, hurrah! This issue can probably be closed now?

**Comment by ndmitchell** [comment]
Yep, was just waiting for our external CI to go green so I could validate it completely. But yes, all good now!
