### ISSUE TITLE
How to "install" targets?

### ISSUE THREAD

**Issue by zjturner** [facebook/buck2#450]
I'm trying to provide a "bridge" between two different build systems to aid in the incremental migration from an existing build system to buck2.  Ideally, I run the buck2 build first and incrementally port targets from the old build system to buck2.  Then, from within the old build system, I refer to the artifacts that buck2 generated, either by referencing some metadata that `buck2 build` outputs, or by being able to programatically reconstruct buck2's output paths from within the old build system.

Normally, a build system will have the concept of an "install" or "package" step that runs after everything has been built.  And it pieces together the outputs from various other parts of the build that ran, and processes them into some final package.  Often this is as simple as just copying all of the executables and runtime dependencies into a single folder so that everything is side by side.  But in my case, I also need to know include paths so that my old build system can include headers from the libraries it's linking against.

I see a few references to an `InstallInfo` provider in the prelude, but I don't see anything that actually makes use of it.  

I'd actually like to find a way to do both things for related but slightly different reasons:
1. When building a target, output a metadata file that contains some information about that target.  For example, given:
```
cxx_library(name = "foo", include_directories = ["include/A", "include/B"])
```

after building that, there should be a file like `foo.config.json` that contains information like:
```
target: {
   "name: "foo",
   "include_directories": [
        "/user/zjturner/home/src/project/foo/include/A",
        "/user/zjturner/home/src/project/foo/include/B"
    ],
    "library": [
        "/user/zjturner/home/build/foo/foo.a"
    ]
}
```

so that the other build can then read this file and parse its in

2: Have all output files of all targets get copied to a single binary directory so that they are all side by side and I don't have to worry about runtime dependencies (e.g. shared objects, data file inputs, etc) at runtime.

And I'd like to find a way to do all of this with the standard buck2 prelude, so I don't have to re-write complicated rules like `cxx_library()` and `cxx_binary()` from scratch.

Is this possible?  Or is there a different recommended approach for bridging build systems for an incremental migration?

**Comment by cjhopman** [comment]
Usually the sort of packaging that you describe would be implemented as normal rules and targets. For something like cxx_binary, it may be difficult to do without exposing additional functionality from cxx_binary itself, given that the binary produced from cxx_binary may encode expected relative paths to the shared libs that it depends on. For some other languages, you may encounter similar challenges.

buck2 does have an install command (the InstallInfo you've found is related to that), but I don't think it would help make the problems above any simpler.

**Comment by thoughtpolice** [comment]
Note that while there's no `install` support right now, you can just do `buck2 build <target-pattern> --show-output` to get a list of output lines that look like this:

```
tilde//aseipp/libedsign:lib buck-out/v2/gen/tilde/15aa248f3a3f0bd9/aseipp/libedsign/__lib__/liblib.a
```

So the first column is the target, and the second is the `DefaultInfo` output of the provider. You can also refer to subtargets e.g. `buck2 build :foo[bar]` or whatever to get more specific.

So, you can probably just use `build --show-output` a bunch to get those outputs from e.g. CMake or whatever original system you're using.

Note that some cases may be handled better by something like `buck2 cquery --output-all-attributes --output-format json` which you could use to e.g. look at all the `exported_headers` or whatever.

**Comment by zjturner** [comment]
> Usually the sort of packaging that you describe would be implemented as normal rules and targets.

don’t these always output to buck-out though?  How would I get the install destination to be outside of the build tree?

**Comment by thoughtpolice** [comment]
I think the idea is that your target creates some distributable artifact (a `.app`, a `.tar.gz`, docker container image, an `.msi`) via `buck2 build <TARGET>`, and then you would just pluck it out and distribute it without buck, after that. I.e. your CI system would do something like this to build a result and copy it to S3:

```bash
SOURCE_DIR=$(buck2 root -k project)
OUTPUT_ARTIFACT=$(buck2 build cell//name/of:target --show-output | awk '{print $2}')
aws s3 cp $SOURCE_DIR/$OUTPUT_ARTIFACT s3//$BUCKET_NAME/$OUTPUT_ARTIFACT
```

**Comment by zjturner** [comment]
Yea I suppose that works.  It's not the end of the world, just means I have to build automation on top of raw buck2 to run a full build end to end.

**Comment by cbarrete** [comment]
(How) did you end up solving this @zjturner?

I have the same issue now where I need to package buck2-built C++ binaries, but there seems to be no straightforward way to accomplish this.
I've given up on using BXL for that, as it was becoming a pile of hacks/heuristics to figure out which targets/outputs to include or not, to deduplicate them, to handle symlinks, etc. Add on top of that internal toolchain/rules quirks the result is starting to look quite brittle.

My next approach would be to walk the binary's rpath outside of buck2 and figure out what to package this way, but it's not ideal either and only covers libraries (and not e.g. resource files).

Could someone from Meta comment as to what their general approach to packaging/installing buck2 targets is internally?

**Comment by zjturner** [comment]
I have not implemented a solution for this yet.  But for "which targets / outputs to include" my first thought would be to put metadata on the target, and read that metadata from bxl.  For whatever reason, reading metadata from bxl doesn't actually work right now, but there's a workaround where you can get it to work (https://github.com/facebook/buck2/issues/521).

A second option would be to copy all executables and shard libraries to the same directory.  usually that works and is good enough.

A third option would be a custom rule that you write which you can give it as input a manifest file describing the package layout, and your rule can parse that manifest file and use the buck2 rule api to move outputs from dependent targets around according to whatever layout the manifest specifies.

Again, haven't tried any of these options, but I would expect something along those lines to be workable.

**Comment by cbarrete** [comment]
Thanks for your input, for now I've hacked up a script that implements the second option, but it's quite brittle when transitive dependencies are involved and requires special attention for each rule that is involved.

As you said, those options are workable, but I also want them to be reasonable, ideally requiring nothing special from users, so that they can just write `cxx_binary`/`cxx_library` targets.
