### ISSUE TITLE
cxx zig toolchain does not work on macOS

### ISSUE THREAD

**Issue by jazzdan** [facebook/buck2#470]
Again: totally understand that the zig toolchain is experimental!

Following on from #461, upgrading to a newer release of zig fixes some of the problems but there's still at least one more issue:

```
buck2 build //:hello
Action failed: root//:hello (cxx_link_executable)
Local command returned non-zero exit code 1
Reproduce locally: `env -- "BUCK_SCRATCH_PATH=buck-out/v2/tmp/root/213ed1b7ab869379/__hello__/cxx_link_executable" buck- ...<omitted>... b7ab869379/__cxx__/zig_cxx.sh @buck-out/v2/gen/root/213ed1b7ab869379/__hello__/hello.linker.argsfile (run `buck2 log what-failed` to get the full command)`
stdout:
stderr:
error: unsupported linker arg: -oso_prefix
Build ID: 6e276212-16a3-4b86-b1b2-1ba46fef788c
Network: Up: 0B  Down: 42MiB
Jobs completed: 52. Time elapsed: 6.9s.
Cache hits: 0%. Commands: 4 (cached: 0, remote: 0, local: 4)
BUILD FAILED
Failed to build 'root//:hello (prelude//platforms:default#213ed1b7ab869379)'
```

The pertinent part seems to be: `error: unsupported linker arg: -oso_prefix`.

## Steps to reproduce
1. `git clone git@github.com:jazzdan/buck2_zig_toolchain_macos_bug.git`
2. `cd buck2_zig_toolchain_macos_bug`
3. `buck2 build //:hello`

```
sw_vers
ProductName:		macOS
ProductVersion:		13.6
BuildVersion:		22G120
```

cc @aherrmann

**Comment by ndmitchell** [comment]
Thanks for the info - I'll document it!

**Comment by ndmitchell** [comment]
@aherrmann - worth applying the patch to pretend the macos linker for Zig is `gnu` in the meantime? It seems the alternative definitely fails, and while `gnu` might not completely work, at least it works a bit?

**Comment by aherrmann** [comment]
@ndmitchell Indeed, it's probably worth it. I've opened https://github.com/facebook/buck2/pull/526 for it.

**Comment by ndmitchell** [comment]
Thanks @aherrmann !
