### ISSUE TITLE
How to get absolute path of a source file from bxl?

### ISSUE THREAD

**Issue by zjturner** [facebook/buck2#479]
I've got a bxl function that looks like this:

```
def gen_cpp_props_impl(ctx):
    for target in ctx.configured_targets('...'):
        ctx.output.print(target.label)
        # I know I can just print str(target.buildfile_path), but bare with me for a while.
        ctx.output.print("    BUILD File Path: " + str(target.buildfile_path.path))
```

That returns an error like this:

```
D:\src\foo>buck2 bxl root//build-scripts/gen_cpp_props.bxl:gen_cpp_props
File changed: root//build-scripts/gen_cpp_props.bxl
Traceback (most recent call last):
  File <builtin>, in <module>
error: Object of type `file_node` has no attribute `path`
 --> build-scripts/gen_cpp_props.bxl:8:56
  |
8 |         ctx.output.print("    BUILD File Path: " + str(target.buildfile_path.path))
  |                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
Build ID: ebedec15-d229-40cc-89c0-c2f9fe8a990b
Network: Up: 0B  Down: 0B
Jobs completed: 3. Time elapsed: 0.2s.
BXL FAILED
```

I looked [here](https://github.com/facebook/buck2/blob/1a42ce5806ee93f54925a0cee451cfc3bae96d3f/app/buck2_core/src/build_file_path.rs#L51) and there is in fact a `path()` method.

So I figured it's something to do with the starlark binding.  And anyway, it says it's an object of type `file_node`.  So I tracked that down to [here](https://github.com/facebook/buck2/blob/1a42ce5806ee93f54925a0cee451cfc3bae96d3f/app/buck2_bxl/src/bxl/starlark_defs/file_set.rs#L131):

My rust isn't great, but from what I can tell there's not much in there.  It looks like it's an object of type `CellPath`, But I can't figure out how to access that either.

Ultimately, I want to convert this path into an absolute path on disk.  Which I guess means resolving a cell path to a location on the actual disk, but even if I had a `CellPath`, I'm not sure how to do that either.

Any suggestions?

**Comment by davidbarsky** [comment]
I'd take a look at https://buck2.build/docs/api/bxl/fs/#fsabs_path_unsafe. Note that this function will likely return the wrong answer if your BXL script ever runs on RE, which may or may not be an issue.

**Comment by zjturner** [comment]
Not an issue.  This is for experimenting with local IDE project generation, where you need to specify absolute paths in the IDE project file.  Will take a look, thanks!
