### ISSUE TITLE
How to consume http_archive C++ headers?

### ISSUE THREAD

**Issue by jhdub23** [facebook/buck2#480]
I'm experimenting with `http_archive`, I but can't figure out how to consume it in a simple C++ program.  I'm using the [buck2 getting started](https://buck2.build/docs/getting_started/) guide and incorporating [easylogging](https://github.com/abumq/easyloggingpp) as a simple test (header only version).

I modifed "main.cpp" to `#include <easylogging++.h>`, but I can't figure out the correct BUCK build file to get this to compile.  In the BUCK file, I added/modified:

```
http_archive(
  name = 'archive-easylogging',
  urls = [
    'https://github.com/abumq/easyloggingpp/releases/download/9.89/easyloggingpp_v9.89.tar.gz'
  ],
  sha256 = 'f91f2d3d560513c8a595f5ab0b10075e8fa7ee5eb92147a0925bc9a4183e0c48',
  visibility = ["PUBLIC"],
  sub_targets = ['easylogging++.h']
)

cxx_binary(
    name = "main",
...
    deps = [
        ":print",
        ":archive-easylogging",
    ],
    preprocessor_flags = ["-I$(location :archive-easylogging)"],
)
```

The above fails to compile as the `easylogging++.h` header file cannot be found.  I'm sure that I'm doing something wrong, but I'm new to buck/buck2/bazel.  The correct preprocessor_flags are not getting passed to the compiler.  I've searched the docs and issues, but I'm stumped.  Can someone show me the correct way to consume http_archives for C++?

**Comment by zjturner** [comment]
What *is* being passed for `-I`?  Open your argsfile and see what its actually putting there.  `buck2 log what-failed` and then `cat` the argsfile that it references in the command line.

Your example looks correct to me (except that you dont' need the `sub_targets` attribute on the `http_archive` rule), and the same as what I'm doing in a situation where it works.

**Comment by jhdub23** [comment]
Commenting out the preprocessor_flags line has no effect on the args file.  Additional trace:

```bash
>buck2 log what-failed
Showing commands from: buck2 build //:main
build	root//:print (prelude//platforms:default#524f8da68ea2a374) (cxx_compile main.cpp)	local	env -- "TMPDIR=<<redacted>>/buck2/examples/hello_world/buck-out/v2/tmp/root/524f8da68ea2a374/__print__/cxx_compile/main.cpp" "BUCK_SCRATCH_PATH=buck-out/v2/tmp/root/524f8da68ea2a374/__print__/cxx_compile/main.cpp" "BUCK2_DAEMON_UUID=92a0cf09-03d4-425a-9b0d-9f2edac0475e" "BUCK_BUILD_ID=99ba42f0-f181-4798-811a-b626969b8a32" g++ -o buck-out/v2/gen/root/524f8da68ea2a374/__print__/__objects__/main.cpp.o @buck-out/v2/gen/root/524f8da68ea2a374/__print__/.cpp.argsfile -c ./main.cpp
>cat buck-out/v2/gen/root/524f8da68ea2a374/__print__/.cpp.argsfile
"-fdiagnostics-color=always"
-I
buck-out/v2/gen/root/524f8da68ea2a374/__print__/buck-headers
```

**Comment by zjturner** [comment]
If that's the case, then something else must be going on unrelated to `http_archive`.  What if you change the line to `preprocessor_flags = ["-Ifoo"]`?  Does nothing still show up?

**Comment by jhdub23** [comment]
@zjturner `preprocessor_flags = ["-Ifoo"]` works.  Output of the `*.argsfile`:

``` text
"-fdiagnostics-color=always"
-I
buck-out/v2/gen/root/524f8da68ea2a374/__print__/buck-headers
-Ifoo
```

It's only the specific `-I$(location...` that seems to be the problem.  I hard-coded the resolved location and buck2 ignores the specific path:

```
    #1 preprocessor_flags = ["-Ibuck-out/v2/gen/root/524f8da68ea2a374/foo"]
    #2 preprocessor_flags = ["-Ibuck-out/v2/gen/root/524f8da68ea2a374/__archive-easylogging__/foo"]
    #3 preprocessor_flags = ["-Ibuck-out/v2/gen/root/524f8da68ea2a374/__archive-easylogging__/archive-easylogging_foo"]
    #4 preprocessor_flags = ["-Ibuck-out/v2/gen/root/524f8da68ea2a374/__archive-easylogging__/archive-easylogging"]
```
 In the above, `#1` - `#3` with the artificial "foo" works, as I see the appropriate "-I" statement in the `*.argsfile`.  The `#4` example does not get passed to the `*.argsfile`.

I don't know if this makes any difference, but I did modify the example to work with gcc.  In the `toolchains/BUCK` file:

```
# toolchains/BUCK
load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")

system_cxx_toolchain(
    name = "cxx",
    compiler_type = "gcc",
    compiler = "gcc",
    cxx_compiler = "g++",
    linker = "g++",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)
```

Can someone verify that you get the same behavior? It should be very easy to reproduce.  I can also create a fork with the modifications if that makes it easier.

**Comment by jhdub23** [comment]
Update:  Using `preprocessor_flags = ["-Ibuck-out/v2/gen/root/524f8da68ea2a374/__archive-easylogging__/archive-easylogging/foo"]` also works.  It seems that something is filtering out the preprocessor flag when the top-level archive path is used.

**Comment by jhdub23** [comment]
Problem found.  It turns out that the issue has nothing to do with `preprocessor_flags` or `http_archive()`.  The `main.cpp` file was incorrectly being compiled within `cxx_library`.  The pull request #501 fixes this issue so that things work as expected.

**Comment by jhdub23** [comment]
The `http_archive` and `preprocessor_flags` now work as expected when using the buck2 hello world getting started example as a starting point.
