### ISSUE TITLE
C++ LSP Support

### ISSUE THREAD

**Issue by SvenKratzEasel** [facebook/buck2#484]
Sorry, I'm a bit of a newbie when it comes to buck2 so this might already be a solved problem: 

I started a C++ project, but I can't figure out how to get LSP support for the output. I'd really like to get as much help as possible from my editor (VSCode or Vim), but can't get buck2 to output the compilation database for my target. Any suggestions?

**Comment by zjturner** [comment]
buck2 can already output a compilation database for an individual target.  You can do this by building the `compilation-database` subtarget.  For example, given the target `root//src:foo`, you can build a compilation database for that target by doing `buck2 build root//src:foo[compilation-database]`.

Unfortunately, buck2 currently only supports generating a compilation database per-target.  This doesn't really map well to how most LSPs operate, which expect a compilation database for your entire project.  I actually just finished (5 minutes ago actually!) writing a bxl that can generate a compilation database for your entire build.

It probably has some imperfect edge cases, but I've tested it locally and it works very well with VSCode.  Put [this file](https://gist.github.com/zjturner/0a9c99d8e4fa50dbd7a74d2c1637cc63) somewhere in the root of your tree (let's say you put it at `<root>/bxl/compile_commands.bxl`) and then generate the compilation database as `buck2 bxl root//bxl/compile_commands.bxl:gen_compilation_database > compile_commands.json`.

This will dump a `compile_commands.json` into the root of your source directory.

I'm actually interested to see if you run into any problems with it.  Perhaps I should try upstreaming this into the examples folder.

**Comment by SvenKratzEasel** [comment]
Thanks, I will try it out.

**Comment by SvenKratzEasel** [comment]
@zjturner the script outputs an empty json file.

**Comment by zjturner** [comment]
What is the full cell path to your target?  Something like `root//something:my_target`?

**Comment by SvenKratzEasel** [comment]
Yes, it follows this path. This is what happens when I try to build compilation-database:

```
buck2 build root//my_project:my_binary[compilation-database]

zsh: no matches found: root//my_project:my_binary[compilation-database]
```

**Comment by Release-Candidate** [comment]
> zsh: no matches found: root//my_project:my_binary[compilation-database]

The problem is that `[` (and `]`) is a special shell character, so you have to quote it.

`buck2 build 'root//my_project:my_binary[compilation-database]'` should work. But you better use the version that includes the header file information: `buck2 build 'root//my_project:my_binary[full-compilation-database]'`.

In my vcpkg Example and Conan Example I used a Python script to concat all jsons to a single `compile_command.json`:
[Cxx-Buck2-vcpkg-Examples - concat_compile_cmds](https://github.com/Release-Candidate/Cxx-Buck2-vcpkg-Examples/tree/main/concat_compile_cmds) and [Cxx-Buck2-Conan-Examples - concat_compile_cmds](https://github.com/Release-Candidate/Cxx-Buck2-Conan-Examples/tree/main/concat_compile_cmds)
The usage:
```python
load("//concat_compile_cmds:defs.bzl", "concat_compile_cmds")

concat_compile_cmds(
    name="compile_commands",
    files=[
        "//app:app[full-compilation-database]",
        "//lib:library[full-compilation-database]",
        "//test:test[full-compilation-database]",
    ],
)
```
[Cxx-Buck2-vcpkg-Examples - BUCK](https://github.com/Release-Candidate/Cxx-Buck2-vcpkg-Examples/blob/main/BUCK)

**Comment by SvenKratzEasel** [comment]
Thanks for the help @Release-Candidate. Unfortunately I'm having no luck with these efforts. The command now runs, but it produces an empty json file. The binary imports a mix of `.hpp` internal to the project and external `.h` files. Could the `.hpp` files cause adverse issues?

**Comment by Release-Candidate** [comment]
No, that shouldn't be a problem, I'm doing the same. 

The empty JSON is the one this 

```text
buck2 build '/my_project:my_binary[full-compilation-database]' --show-ouput
```

 points to, I suppose?
 
 If that's the case and the binary successfully compiles - as you've said - the problem is elsewhere. May be a bug in the generation of the `compile_commands.json` too. It now depends on your actual C++ toolchain configuration and target configurations.

**Comment by zjturner** [comment]
Id be curious what `buck2 aquery deps(//my_project:my_binary) —output-all-attributes` shows.  Because it really sounds like your toolchain definition is messed up.

**Comment by Release-Candidate** [comment]
> Id be curious what `buck2 aquery deps(//my_project:my_binary) —output-all-attributes` shows. Because it really sounds like your toolchain definition is messed up.

And don't forget to quote the parens (again, special shell characters) and use two hyphens instead of the long one above: 

```text
buck2 aquery 'deps(//my_project:my_binary)' --output-all-attributes
```

**Comment by SvenKratzEasel** [comment]
This is how it looks:

```
File changed: root//my_project/src/lib/output_writing.hpp
Build ID: f07d2779-c5ab-4253-ac08-84fb6f45c651
Jobs completed: 2. Time elapsed: 0.0s.
{
  "root//my_project:my_target (prelude//platforms:default#213ed1b7ab869379)": {
    "kind": "analysis"
  },
  "(target: `root//my_project:my_target (prelude//platforms:default#213ed1b7ab869379)`, id: `1`)": {
    "kind": "symlinkeddir",
    "category": "symlinked_dir",
    "identifier": "buck-private-headers",
    "inputs": "",
    "outputs": "",
    "executor_configuration": "Local + use persistent workers false"
  },
  "(target: `root//my_project:my_target (prelude//platforms:default#213ed1b7ab869379)`, id: `4`)": {
    "kind": "write",
    "category": "write",
    "identifier": ".cpp.argsfile",
    "inputs": "",
    "outputs": "",
    "contents": "-Xclang\n-fdebug-compilation-dir\n-Xclang\n.\n-fcolor-diagnostics\n-I\nbuck-out/v2/gen/root/213ed1b7ab869379/my_project/__my_target__/buck-private-headers\n-I/opt/homebrew/include/pcl-1.13\n-I/opt/homebrew/include/eigen3\n-I/opt/homebrew/include\n-I/opt/homebrew/include/vtk-9.2\n\"-std=c++17\"",
    "absolute": "false",
    "executor_configuration": "Local + use persistent workers false"
  },
  "(target: `root//my_project:my_target (prelude//platforms:default#213ed1b7ab869379)`, id: `6`)": {
    "kind": "run",
    "category": "cxx_compile",
    "identifier": "src/my_target.cpp (pic)",
    "inputs": "",
    "outputs": "",
    "cmd": "[clang++, -o, buck-out/v2/gen/root/213ed1b7ab869379/my_project/__my_target__/__objects__/src/my_target.cpp.pic.o, -fPIC, @buck-out/v2/gen/root/213ed1b7ab869379/my_project/__my_target__/.cpp.argsfile, -c, my_project/src/my_target.cpp]",
    "executor_preference": "Default",
    "always_print_stderr": "false",
    "weight": "1",
    "dep_files": "[]",
    "metadata_param": "None",
    "no_outputs_cleanup": "false",
    "allow_cache_upload": "false",
    "allow_dep_file_cache_upload": "false",
    "executor_configuration": "Local + use persistent workers false"
  },
  "(target: `root//my_project:my_target (prelude//platforms:default#213ed1b7ab869379)`, id: `24`)": {
    "kind": "write",
    "category": "write",
    "identifier": "filelist-executable.txt",
    "inputs": "",
    "outputs": "",
    "contents": "buck-out/v2/gen/root/213ed1b7ab869379/my_project/__my_target__/__objects__/src/my_target.cpp.pic.o",
    "absolute": "false",
    "executor_configuration": "Local + use persistent workers false"
  },
  "(target: `root//my_project:my_target (prelude//platforms:default#213ed1b7ab869379)`, id: `25`)": {
    "kind": "write",
    "category": "write",
    "identifier": "my_target.linker.argsfile",
    "inputs": "",
    "outputs": "",
    "contents": "-o\nbuck-out/v2/gen/root/213ed1b7ab869379/my_project/__my_target__/my_target\n-Wl,-oso_prefix,.\n-L/opt/homebrew/lib\n-lvtkCommonCore-9.2\n-lvtkCommonDataModel-9.2\n-lvtkCommonMath-9.2\n-lvtkCommonExecutionModel-9.2\n-lvtkIOImage-9.2\n-lvtksys-9.2\n-lvtkFiltersCore-9.2\n-lvtkRenderingCore-9.2\n-lvtkRenderingLOD-9.2\n-lvtkFiltersSources-9.2\n-lvtkImagingCore-9.2\n-lpcl_visualization\n-lpcl_common\n-lpcl_io\n-lpcl_filters\n-lfmt\n-Xlinker\n-filelist\n-Xlinker\nbuck-out/v2/gen/root/213ed1b7ab869379/my_project/__my_target__/filelist-executable.txt",
    "absolute": "false",
    "executor_configuration": "Local + use persistent workers false"
  },
  "(target: `root//my_project:my_target (prelude//platforms:default#213ed1b7ab869379)`, id: `26`)": {
    "kind": "run",
    "category": "cxx_link_executable",
    "identifier": "",
    "inputs": "",
    "outputs": "",
    "cmd": "[clang++, @buck-out/v2/gen/root/213ed1b7ab869379/my_project/__my_target__/my_target.linker.argsfile]",
    "executor_preference": "LocalPreferred",
    "always_print_stderr": "false",
    "weight": "1",
    "dep_files": "[]",
    "metadata_param": "None",
    "no_outputs_cleanup": "false",
    "allow_cache_upload": "false",
    "allow_dep_file_cache_upload": "false",
    "executor_configuration": "Local + use persistent workers false"
  }
}
```

**Comment by SvenKratzEasel** [comment]
--output-all-attributes seems to output something in the buck-out directory, so I'll probably be able to work with that. Thanks for the help!

**Comment by SvenKratzEasel** [comment]
VSCode C++ extension works if `compile_commands.json` output file of the following command is added as the compilation database:

`buck2 build '//my_project:my_target[full-compilation-database]' --show-output`

Copy `compile_commands.json` from `buck-out` folder to project root if desired.

**Comment by ndmitchell** [comment]
It sounds like we should probably document the C++ LSP better. Where should such documentation go? What should it say? (We use an internal version of VS Code, but with enough differences that I'm not sure we at Meta know how to make it work)

**Comment by Release-Candidate** [comment]
Good question, I'm not sure either. Maybe the examples?

The steps are as follows for clangd, which works in VS (if I'm not mistaken), VS Code, Emacs, vim and similar, IntelliJ's Lion, .... Should work with MS' LSP in VS Code too:

- run the `full-compilation-database` subtargets for all targets
- concatenate these JSONs into one
- change the relative path in the field `directory` to an absolute one
- copy that concatenated JSON into the repository's root directory (or wherever the editor/LSP wants it)

I've made a Python script that does that for my C++ Examples: [Cxx-Buck2-vcpkg-Examples - concat_compile_cmds](https://github.com/Release-Candidate/Cxx-Buck2-vcpkg-Examples/tree/main/concat_compile_cmds) (and [Cxx-Buck2-Conan-Examples - concat_compile_cmds](https://github.com/Release-Candidate/Cxx-Buck2-Conan-Examples/tree/main/concat_compile_cmds))

**Comment by Release-Candidate** [comment]
Talking about LSP support, for OCaml this could be documented somewhere too, a `.merlin` file has to be generated for Merlin and/or the LSP, and the LSP needs the argument `--fallback-read-dot-merlin`.

[Using Buck 2 with OCaml-LSP or Merlin](https://github.com/Release-Candidate/OCaml-Buck-2-Examples#using-buck-2-with-ocaml-lsp-or-merlin)

**Comment by ndmitchell** [comment]
Those are really good notes!

**Comment by zjturner** [comment]
@ndmitchell  The bxl I post earlier, with some modifications I have not published yet, is about 10x faster than merging all compilation databases.  Is there interest in me upstreaming it?
