### ISSUE TITLE
custom cxx_toolchain configuration fails to accept archiver

### ISSUE THREAD

**Issue by hutm** [facebook/buck2#494]
I am trying to configure a custom cxx_toolchain:
```
cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
    c_compiler="third-party/build/gcc/bin-linux-x86_64/gcc",
    linker="third-party/build/gcc/bin-linux-x86_64/g++",
    linker_type="gnu",
    cxx_compiler="third-party/build/gcc/bin-linux-x86_64/g++",
    assembler="third-party/build/gcc/bin-linux-x86_64/as",
    nm="third-party/build/binutils-wrapper-2.40/bin/nm",

    archiver_type = "gnu",
    archiver_supports_argfiles = True,
    archiver="third-party/build/binutils-wrapper-2.40/bin/ar",
    objcopy_for_shared_library_interface="shared",
    shared_library_interface_type = "shared",
    strip = "third-party/build/binutils-wrapper-2.40/bin/strip",
)
```
buck2 cannot accept archiver:
```
Error coercing attribute `archiver` of `toolchains//:cxx`

       Caused by:
           0: Error coercing attribute `archiver` of type `attrs.dep()`
           1: Error coercing "third-party/build/binutils-wrapper-2.40/bin/ar"
           2: Invalid absolute target pattern `third-party/build/binutils-wrapper-2.40/bin/ar` is not allowed
```
Is there a sample configuration of a `cxx_toolchain` that can serve as a reference?

**Comment by Release-Candidate** [comment]
> Invalid absolute target pattern `third-party/build/binutils-wrapper-2.40/bin/ar` is not allowed

That means that Buck is reading that as a target pattern instead of relative path. Try adding a `./`.

**Comment by cjhopman** [comment]
The issue is that the archiver attr, and probably several of the others, is expecting to be passed a target for a binary, but it looks like you are passing a file. You can probably write a trivial sh_binary target to represent it.

**Comment by zjturner** [comment]
> The issue is that the archiver attr, and probably several of the others, is expecting to be passed a target for a binary, but it looks like you are passing a file. You can probably write a trivial sh_binary target to represent it.

But why does the error message say that it’s of type attr.dep() when it appears to be attr.source in the prelude?

**Comment by cjhopman** [comment]
You probably mean it's set to attr.source() here: https://github.com/facebook/buck2/blob/main/prelude/decls/cxx_rules.bzl#L864?

So this is a bit deceptive. The attr definitions in decls may be overridden in other parts of the prelude (historically, what's in decls was actually automatically extracted from buck1 by a command like `buck1 audit ruletypes --specs --json` and regularly updated so we weren't changing it directly). Specifically for cxx_toolchain, I suspect that that's here: https://github.com/facebook/buck2/blob/edc32890d0c11275352a7a7865968af2ee50792c/prelude/cxx/cxx_toolchain.bzl#L162

**Comment by Release-Candidate** [comment]
> The issue is that the archiver attr, and probably several of the others, is expecting to be passed a target for a binary, but it looks like you are passing a file. 

Btw. why does the documentation just say `str` instead of the real types (like `attrs.source()`, `attrs.dep()` ...)? It's autogenerated, right? It isn't wrong, but all it tells us is that it isn't a `bool` or a list or a dict (AFAIK that are all possible types in the API doc). And if I have to lookup the sources anyway, is there a way to link the source of each rule in the documentation?
https://buck2.build/docs/api/rules/#cxx_toolchain

**Comment by hutm** [comment]
@zjturner , can you share your full linux toolchain config? I am trying to adapt your windows toolchain but failing to make it work (might be missing some imports):
```
def _my_msvc_toolchain_impl(ctx):
    msvc_bin_dir = "third-party/build/gcc/bin-linux-x86_64/"
    binutils_dir = "third-party/build/binutils-wrapper-2.40/bin/"

    additional_linker_flags = []
    archiver = binutils_dir + "ar"
    asm_compiler = msvc_bin_dir + "as"
    c_compiler = msvc_bin_dir + "gcc"
    cxx_compiler = msvc_bin_dir + "g++"
    linker = msvc_bin_dir + "ld"

    return [
        DefaultInfo(),
        CxxToolchainInfo(
            mk_comp_db = ctx.attrs.make_comp_db,
            linker_info = LinkerInfo(
                linker = RunInfo(args = linker),
#                linker_flags = msvc_cxx_linker_options(),
                archiver = RunInfo(args = [archiver]),
                archiver_supports_argfiles = True,
                archiver_type = "linux",
                generate_linker_maps = False,
                lto_mode = LtoMode("none"),
                type = "linux",
                link_binaries_locally = True,
                archive_objects_locally = True,
                use_archiver_flags = False,
                static_dep_runtime_ld_flags = [],
                static_pic_dep_runtime_ld_flags = [],
                shared_dep_runtime_ld_flags = [],
                independent_shlib_interface_linker_flags = [],
                shlib_interfaces = ShlibInterfacesMode("disabled"),
                link_style = LinkStyle("static"),
                link_weight = 1,
                binary_extension = "",
                object_file_extension = "obj",
                shared_library_name_format = "{}.so",
                shared_library_versioned_name_format = "{}.so",
                static_library_extension = "a",
                force_full_hybrid_if_capable = False,
                is_pdb_generated = is_pdb_generated("linux", []),
                shared_library_name_default_prefix="",
            ),
            bolt_enabled = False,
        ),
    ]

my_msvc_toolchain = rule(
    impl = _my_msvc_toolchain_impl,
    attrs = {
        "linker_wrapper": attrs.default_only(attrs.dep(providers = [RunInfo], default = "prelude//cxx/tools:linker_wrapper")),
        "make_comp_db": attrs.default_only(attrs.dep(providers = [RunInfo], default = "prelude//cxx/tools:make_comp_db")),
    },
    is_toolchain_rule = True,
)
``` 
failing with 
```
    6: error: Variable `CxxToolchainInfo` not found
         --> prelude/toolchains/cxx_custom.bzl:14:9
          |
       14 |         CxxToolchainInfo(
          |         ^^^^^^^^^^^^^^^^
```

**Comment by zjturner** [comment]
In the case above you just need to load() it from the prelude.  Grep prelude to find the appropriate bzl file.  

I can post my linux one tomorrow, but be warned it’s quite incomplete since Ive mostly been focusing on windows

**Comment by hutm** [comment]
@zjturner , please share your linux config when you have a chance

**Comment by zjturner** [comment]
It's almost the same as `system_cxx_toolchain`.

toolchain file: https://gist.github.com/zjturner/d95c0be88a3abba014c96205b56ff091

BUCK file: https://gist.github.com/zjturner/fe6fc013b7b37e72638d0c5ffddf7b37

**Comment by ndmitchell** [comment]
In general I try and use `system_cxx_toolchain` instead of `cxx_toolchain` (which is designed for Buck1 compatibility). It doesn't quite support all the fields you want to override, so you probably need to modify it.

@zjturner - your toolchain seems like it has enhancements over our open source one. Anything we should upstream?

**Comment by zjturner** [comment]
Ill diff it after the holidays and see, i have something else to upstream as well (compilation database bxl) so id like to get in the habit of contributing myself

**Comment by hutm** [comment]
thanks @zjturner ! closing this since I was was able to unblock myself
