### ISSUE TITLE
Is it possible to have a rule forward to another rule?

### ISSUE THREAD

**Issue by zjturner** [facebook/buck2#496]
If I do this:

```
def _inner_impl(ctx: AnalysisContext) -> list[Provider]:
    return [DefaultInfo()]

def _outer_impl(ctx: AnalysisContext) -> list[Provider]:
    return inner()

inner = rule(
    attrs = {},
    impl = _inner_impl
)

outer = rule(
    attrs = {},
    impl = _outer_impl
)
```

I get the following error:

```
BUILD FAILED
Error running analysis for `root//:outer (foo//platforms:my-platform#23b3e4bdecafe14a)`

Caused by:
    Traceback (most recent call last):
      File <builtin>, in <module>
      * foo/test_rule.bzl:8, in _outer_impl
          return inner()
    error: This function is unavailable during analysis (usual solution is to place the information on a toolchain)
     --> foo/test_rule.bzl:8:12
      |
    8 |     return inner()
      |            ^^^^^^^
```

I was experimenting with the idea of wrapping rules like `cxx_library()` to modify / change up the arguments before I pass them in.  I feel like it gives me the ability to generate better error messages when the user does something wrong.

My guess is you just can't do this, but figured it was worth asking about.

**Comment by cormacrelf** [comment]
You can make a macro.

```Python
def wrapped_cxx_library(**kwargs):
    srcs = kwargs.pop("srcs");
    srcs.append("file.hh");
    native.cxx_library(srcs = srcs, **kwargs)
```

You don't need to return anything, rules don't return anything when you call them anyway (only the impl functions do). You can call multiple rules, and connect up the outputs of one to the inputs of the other, by constructing

```python
whatever = "{}-whatever".format(name)
cxx_library(name = whatever, ...)

cxx_library(..., deps = kwargs.pop("deps") + [":{}".format(whatever), **kwargs)
```

**Comment by zjturner** [comment]
I'm using macros for this purpose right now, and it generally works ok but sometimes I wish I had access to some of the things in a rule impl's context structure.

**Comment by cjhopman** [comment]
The `inner()` function is a function that declares a target (and does a bunch of other stuff). As the error message indicates, you cannot do that during analysis. You could, however, call the `_inner_impl()` function if you wanted.

**Comment by zjturner** [comment]
Yea, unfortunately I can't do that unless I have access to the impl.  So I can't do it, for example, if I want to forward to `cxx_library`.  In any case, I can continue with just using macros, I can still solve the problem I was having, just not as nicely as if I had the full power of a rule.
