### ISSUE TITLE
`glob()` can only be called from a buildfile context, current context is bzl

### ISSUE THREAD

**Issue by zjturner** [facebook/buck2#497]
```
# BUCK
load(":my_cxx_library.bzl", "my_cxx_library")

my_cxx_library(name = "foo")


# my_cxx_library.bzl
def my_cxx_library(name:str, srcs=glob(["src/**/*.cpp"])):
    cxx_library(name=name, srcs=srcs)
```

When I try to build the target foo, I get an error:

> error: `glob()` can only be called from a build file context; current file context is Bzl

However, some googling and history suggests this wasn't always the case.  [This](https://github.com/airbnb/BuckSample/blob/master/Config/buck_rule_macros.bzl) is from buck1, but it shows this code snippet:

```
def first_party_library(
        name,
        has_objective_c = False,
        has_cpp = False,
        internal_headers = None,
        extra_xcode_files = [],
        mlmodel_generated_source = [],
        deps = [],
        frameworks = [],
        info_plist = None,
        info_plist_substitutions = {},
        test_host_app = None,
        run_test_separately = False,
        test_frameworks = [],
        test_deps = [],
        modular = True,
        compiler_flags = None,
        swift_compiler_flags = None,
        warning_as_error = True,
        suppress_warnings = False,
        **kwargs):
    sources = native.glob(["Sources/**/*.swift"])
    ...
```

I also found [this](https://github.com/facebook/buck2/issues/115#issuecomment-1500860910) post from @ndmitchell from back in April:

> For source roots, perhaps a glob in the macro layer?

Was this functionality changed / remove?  Are there any workarounds to allow globbing from a macro?

**Comment by JakobDegen** [comment]
@zjturner I think this is a misunderstanding in how default values for function parameters work. In starlark (and python) the default value is evaluated only once, when the function is defined, not each time it is called. That means that

```
def my_cxx_library(name:str, srcs=glob(["src/**/*.cpp"])):
    cxx_library(name=name, srcs=srcs)
```

Does not mean

```
def my_cxx_library(name:str, srcs=None):
    if srcs == None:
        srcs = glob(["src/**/*.cpp"])
    cxx_library(name=name, srcs=srcs)
```

But actually means

```
default_srcs = glob(["src/**/*.cpp"])
def my_cxx_library(name:str, srcs=default_srcs):
    cxx_library(name=name, srcs=srcs)
```

Hopefully that should make it more clear why you're seeing the error you're seeing

**Comment by zjturner** [comment]
Yikes, silly oversight on my part 😂
