### ISSUE TITLE
Build cdylib with rust_library?

### ISSUE THREAD

**Issue by SUPERCILEX** [facebook/buck2#524]
How do I build a `cdylib` library?

**Comment by ndmitchell** [comment]
I have no idea - but someone does seem to have writing some support for it in our Rust rules - search `cdylib` in the codebase. Maybe @JakobDegen knows more, as he touched a line mentioning cdylib recently.

**Comment by JakobDegen** [comment]
Rust libraries export a `[shared]` subtarget which produces a cdylib. Note though that if the Rust library has any transitive C/C++ deps, those will be built and linked as DSOs as well, which may or may not be what you want (there's no way to opt out of this behavior atm)

**Comment by SUPERCILEX** [comment]
That works, thanks!

**Comment by Ralith** [comment]
For posterity: The subtarget you want is (now?) `[cdylib]`, *not* `[shared]`.
