### ISSUE TITLE
Errant octal escape strings in prelude docs

### ISSUE THREAD

**Issue by tmfink** [facebook/buck2#579]
In main branch 27cef1bb307c6bd9fe12b04bf4d45a23c5572f12, it seems that there are several instances of accidental octal escapes in:

- app/buck2_server_commands/src/dot/mod.rs
- prelude/decls/core_rules.bzl
- prelude/decls/cxx_rules.bzl
- prelude/decls/ios_rules.bzl

```
# ripgrep search
$ rg --sort=path '\\[0-9]{3}[^\[]' app/ prelude/
app/buck2_server_commands/src/dot/mod.rs
95:///  - Any string of alphabetic ([a-zA-Z\200-\377]) characters, underscores ('_') or digits([0-9]), not beginning with a digit;

prelude/decls/core_rules.bzl
755:                 directory specified in\302\240`http\\_archive()out`.

prelude/decls/cxx_rules.bzl
139:        of the Buck build process. A `cxx_genrule()` exposes\342\200\224through
140:        a set of string parameter macros and variables\342\200\224information about the

prelude/decls/ios_rules.bzl
86:        An `apple_binary()` rule builds a native executable\342\200\224such as an iOS or OSX app\342\200\224from
```

This leads to some garbage characters in some of the rendered HTML docs.

Example from: https://buck2.build/docs/api/rules/#cxx_genrule:
> A cxx_genrule() exposesâthrough a set of string parameter macros and variablesâinformation

**Comment by JakobDegen** [comment]
Fixed on master, thanks!
