### ISSUE TITLE
How to use "buck2 clean" or other commands to delete only the generated files (cache) without killing the daemon?

### ISSUE THREAD

**Issue by yaoddao** [facebook/buck2#608]
Ask a question above，Thanks!

**Comment by krallin** [comment]
This is not a feature that exists in Buck2.

There is buck2 clean --stale that can clean files that were produced by a
previous daemon (assuming you’re using deferred materialization), but that
still won’t clear files the current daemon cares about.

If you think about it though, once you’ve cleared all the outputs there’s
not too much state left in the daemon (only loading and analysis), so what
you’re asking for might be a lot less useful than you think.

**Comment by JakobDegen** [comment]
Yeah, agreed with Thomas. I think it would be good to know what the state that you are expecting to keep around is, we may be able to provide a more helpful answer then
