### ISSUE TITLE
fstring support

### ISSUE THREAD

**Issue by izissise** [facebook/buck2#647]
Hello,
It appears that fstring support is already implemented in starlark-rust but deactivated in Buck2:

https://github.com/facebook/buck2/blob/main/starlark-rust/starlark_syntax/src/dialect.rs#L89 
https://github.com/facebook/buck2/blob/main/app/buck2_interpreter/src/file_type.rs#L24

Currently, there is no straightforward method to activate this feature without recompiling Buck2.

Proposal:
Add a .buckconfig flag to activate fstring support

```
    pub fn dialect(&self, disable_starlark_types: bool, enable_f_strings: bool) -> Dialect {
        let buck_dialect: Dialect = Dialect {
            enable_def: false,
            enable_lambda: true,
            enable_load: true,
            enable_keyword_only_arguments: false,
            enable_types: DialectTypes::Disable,
            enable_load_reexport: false,
            enable_top_level_stmt: false,
            enable_f_strings: enable_f_strings, # gated feature
            ..Dialect::Standard
        };
```

I'm willing to contribute a similar change to buck2, I just don't know where I can add a configuration flag for `.buckconfig`

Thanks,
Hugues

**Comment by stepancheg** [comment]
We want to enable f-strings unconditionally, but internally we are blocked by some internal tooling not supporting it. We will do it eventually, but it will take time.

If you want to implement a buckconfig to enable f-strings, go ahead, and if you do, please assign me as a reviewer.

To implement an option, you need to add a flag to `GlobalInterpreterState` and initialize it like this:

```
diff --git a/fbcode/buck2/app/buck2_interpreter_for_build/src/interpreter/global_interpreter_state.rs b/fbcode/buck2/app/buck2_interpreter_for_build/src/interpreter/global_interpreter_state.rs
--- a/fbcode/buck2/app/buck2_interpreter_for_build/src/interpreter/global_interpreter_state.rs
+++ b/fbcode/buck2/app/buck2_interpreter_for_build/src/interpreter/global_interpreter_state.rs
@@ -12,6 +12,8 @@
 use allocative::Allocative;
 use async_trait::async_trait;
 use buck2_common::dice::cells::HasCellResolver;
+use buck2_common::legacy_configs::dice::HasLegacyConfigs;
+use buck2_common::legacy_configs::key::BuckconfigKeyRef;
 use buck2_core::cells::CellResolver;
 use buck2_futures::cancellation::CancellationContext;
 use buck2_interpreter::dice::starlark_types::GetStarlarkTypes;
@@ -109,12 +111,17 @@
                 let cell_resolver = ctx.get_cell_resolver().await?;
                 let disable_starlark_types = ctx.get_disable_starlark_types().await?;
                 let unstable_typecheck = ctx.get_unstable_typecheck().await?;
+                let enable_f_strings = ctx.parse_legacy_config_property(cell_resolver.root_cell(), BuckconfigKeyRef {
+                    section: "buck2",
+                    property: "starlark_enable_f_strings"
+                }).await?;
 
                 Ok(GisValue(Arc::new(GlobalInterpreterState::new(
                     cell_resolver,
                     interpreter_configuror,
                     disable_starlark_types,
                     unstable_typecheck,
+                    enable_f_strings,
                 )?)))
             }
 ```

**Comment by JakobDegen** [comment]
Discussed a bit more internally - we're just going to turn this on unconditionally in the open source build, and then as soon as we get our linter situation sorted do the same thing for our build. It probably doesn't make sense to support a configurable option for this in the long term
