### ISSUE TITLE
buck-out directory as cachedir

### ISSUE THREAD

**Issue by izissise** [facebook/buck2#650]
Hello,

When building with Buck2, a buck-out directory is created. Users typically do not want this directory to be backed up. Many backup tools ignore directories that contain a file named `CACHEDIR.TAG` with the following content:

```
Signature: 8a477f597d28d172789f06886806bc55
# This file is a cache directory tag created by Buck2.
# For information about cache directory tags, see:
#    http://www.brynosaurus.com/cachedir/
```

More information can be found here: https://bford.info/cachedir/

It would be great if Buck2 could automatically add this file immediately after creating the `buck-out` directory.

Thanks,
Hugues

**Comment by izissise** [comment]
I'm willing to add this, but I'm not sure where to start, it seems it would have its place in buck-prelude?

**Comment by JakobDegen** [comment]
This seems pretty reasonable, I've submitted a change internally to add it

**Comment by JakobDegen** [comment]
Change has landed on master and should go out as a part of the next release, so I'll close this issue. Thanks for the suggestion!
