### ISSUE TITLE
Status of `compatible_with` and alternatives

### ISSUE THREAD

**Issue by cbarrete** [facebook/buck2#713]
Hello,

I am using `compatible_with` to define things like which C++ standard a target is compatible with. I'm using it over `target_compatible_with` since I want the target to be compatible with any of those targets, not all (as they are mutually exclusive).

The [documentation](https://buck2.build/docs/rule_authors/configurations/#buck-v1-compatibility) and [code](https://github.com/facebook/buck2/blob/main/app/buck2_node/src/attrs/internal.rs#L38-L40) state that this is a legacy setting. Should I worry about it going away? If so, what is the recommended alternative?

**Comment by scottcao** [comment]
For target_compatible_with, you can use a select to specify an OR, ex.

```python
target_compatible_with = select({
  "config//os:linux": [], 
  "config//os:macos": [], 
}),
```

Bazel docs have some good examples of this: https://bazel.build/extending/platforms#skipping-incompatible-targets. We should add some to our own docs as well. 

We currently don't have plans to remove `compatible_with` support, but in theory `target_compatible_with` is more expressive because it natively supports both AND and OR expressions.

**Comment by cbarrete** [comment]
I have seen this syntax before, but it has puzzled me, especially the empty list.
Should I read this more or less as "if it's linux or macos, fine, nothing special", but if there was a `DEFAULT` case, we could "point" it to an always incompatible constraint?

What are the semantics of putting something in the rhs lists? Is it a list of constraints that are ANDed together, if the lhs matches?

**Comment by cbarrete** [comment]
Also related, but I can open a separate issue if you prefer: is there a way to select in a `PACKAGE` file? I'm trying to set those constraints per-project to reduce boilerplate, but I'm getting
```
       error: Value must be serializable to JSON to be stored as package value
         --> //path/to/my/project/PACKAGE:12:1
          |
       12 | / write_package_value("my.string", select({
       13 | |     "//build/platforms:cxx-17": [],
       14 | |     "//build/platforms:cxx-20": [],
       15 | | }))
          | |___^
          |
       
    1: Operation `serde::serialize` not supported on type `selector`

```

**Comment by cbarrete** [comment]
In case anyone else hits this, I worked around this by only exposing the `dict` in the `PACKAGE` file and applying `select` at the place that calls `read_package_value`, which is slightly confusing at the call site, but at least works.

**Comment by scottcao** [comment]
PACKAGE values currently have to be JSON serializable and select isn't natively selectable. Perhaps, we should make selects also work in PACKAGE values.

> What are the semantics of putting something in the rhs lists? Is it a list of constraints that are ANDed together, if the lhs matches?

Yes. It's just like any other selects. The selects are resolved by the time buck evaluates `target_compatible_with` and it just becomes a flat list.

**Comment by cbarrete** [comment]
> Perhaps, we should make selects also work in PACKAGE values.

It's not a huge hassle to have the select "on the other side", but that would be nice, especially if it's more or less just a matter of deriving `Serialize`/`Deserialize`.

> Yes. It's just like any other selects.

Given that they're not documented at all right now, having even a small paragraph about how `select` works would have extremely high leverage in terms of helping new users.
