### ISSUE TITLE
Per-PACKAGE transitions

### ISSUE THREAD

**Issue by cbarrete** [facebook/buck2#716]
In case this is an instance of XY problem, here is my use case: I'd like to abstract away one to many transitions, so that e.g. a test target would transition to various platforms (e.g. debug/release across several compilers). Then, users could just run `buck2 test //my/project/...` and all variants would get built and tested.

Now I would like all the implementation details to be abstracted away, and target authors to define in a PACKAGE file containing all the configurations that their project supports/is tested with.

I have hit the following issues:
- transitions can only be defined in .bzl files, not in PACKAGE files. They also cannot be serialized, so they fundamentally cannot be set from PACKAGE files, even if included from a helper .bzl file.
- I can instead just declare the refs in the PACKAGE file, but then Buck complains that the transition I'm defining is not at the top level. This is sort of what I want though, because I want the PACKAGE file of the called to be used, not the one for where the abstraction is defined.
- I tried passing the configuration targets via the `attrs` parameter of the transition function instead, but they get converted to labels, so they're useless by the time I need to use them.

So what I do instead for now is have a macro that generates a few targets with different names and `default_target_platform`s which works, but is quite ugly. It also seems to me like it goes against the point of configuration, because those are completely different targets, rather than just different configurations of the same target.

I think that I could get out of this situation with per-target transitions (?), but those aren't coming anytime soon as I understand it. Is there anything else I can do to achieve this "many builds/tests from a single target using platforms defined in a PACKAGE file"?

**Comment by cbarrete** [comment]
I look forward to this. Do PACKAGE modifiers support one to many "transitions" (I know that transitions are a separate thing)? If so, what does usage look like? Can I do something like the `buck2 test //my/project/...` I mentioned to run tests for multiple configurations at once?

**Comment by cbarrete** [comment]
Thanks a lot for the information, this is very insightful!

What is the difference between using per-target modifiers versus setting the `default_target_platform`? Does it also/just prevent other configurations (e.g. from the command line) from overriding those configurations?

I tried split transitions, but since I couldn't figure out how to define transitions per PACKAGE file, I got stuck, as the opening post explains. I do like the idea of not having separate targets for a given test though. Does that mean that internally, your users have to append a suffix to get the right target to build (e.g. they define `meta_cxx_binary(name = "foo")` but run `buck2 build :foo_release` or something)?

> As in,

I'm all ears if you have something more to share :)

**Comment by scottcao** [comment]
Modifiers are the eventual replacement mechanism for `default_target_platform` and `--target-platforms`, but they behave roughly equivalent currently once the configuration is defined. You can think of it as a more flexible way of defining a configuration. Preventing overrides from cli is really the job of `compatible_with`/`target_compatible_with`.

For cli modifiers, you can do `buck2 build <target>?<constraint1>?<constraint2>` to build with a target once with constraint1 and once with constraint2. There will likely be some shorthand syntax for defining a group of modifiers to use as well so you can imagine something like `buck2 build <target>?all_os` or something similar.

**Comment by scottcao** [comment]
Transitions currently have to be attached to a rule, so you would have to define it in a rule, and then wrap your test targets with that rule. For example, you can define some `test_bundle` rule that accepts test binaries as `deps` and then run a split transition on those deps and merge their providers. That would be one way of going about it. 

> Does that mean that internally, your users have to append a suffix to get the right target to build (e.g. they define meta_cxx_binary(name = "foo") but run buck2 build :foo_release or something)?

I think it sort of depends. Internally, there is a variety of usages, in a large part driven by legacy things. For test targets, I think it may make more sense to use aliases and suffixes with different `default_target_platform`s (or modifiers) because that enables `buck2 test //...` to just work a user. For other binaries, we prefer users to use modifiers on the cli for different variations, ex. `buck2 build :my_bin?release`.

**Comment by cbarrete** [comment]
This all makes a lot of sense, thank you very much! It was bit difficult for me to navigate the intended usages of various features, especially since some of them are meant to be replaced.

I'll close this issue since I basically have an answer to my XY problem: I'll just generate targets for now, at least for tests.
