### ISSUE TITLE
Shadow prelude rules globally

### ISSUE THREAD

**Issue by cbarrete** [facebook/buck2#717]
(How) Is it possible to shadow prelude rules in favor of our own/a macro? I have thin wrappers around C++ rules that I wish to enforce the usage of to avoid mistakenly calling the prelude ones. I would strongly prefer no to require explicitly `load` this override if possible.

I remember @dtonlay saying something about how Meta's `rust_binary` rule (or something similar) wrapped the prelude, so I assume that this is possible.

**Comment by cbarrete** [comment]
@JakobDegen Is there any documentation about this somewhere?

**Comment by cbarrete** [comment]
I've stumbled across `app/buck2_interpreter/src/import_paths.rs`, which looks like I want:

`.buckconfig`
```
[buildfile]
name = BUILD
includes = root//foo.bzl
```

`root//foo.bzl`
```starlark
def cxx_library():
    print("I'm a library")
```

`BUILD`
```starlark
cxx_library()
```

Prints as expected when evaluating that file. Am I abusing this? Should I expect it to break? It looks like LSP Go To Definition doesn't work with it, but that's a minor annoyance I can live with.

cc Buck2 wizard @ndmitchell

**Comment by cjhopman** [comment]
Yeah, you can use buildfile.includes to do this. We used to do that, but now ours just looks more like:

```
def cxx_library():
  fail("use load('some//path.bzl', 'cxx_library') instead")
```

And so all used rules have explicit loads associated with them.

Another alternative is to use your own prelude, which could feasibly load symbols from the standard one. The way the prelude works is that `prelude//prelude.bzl` needs to have a `native` symbol and then all items on that symbol will be available to build files

**Comment by cbarrete** [comment]
Ah that makes sense, thank you! I think that we'll do the exact same thing, that removes a bunch of magic and will unbreak Go To Definition.

I tried to make a custom prelude that loads the upstream one, but failed miserably because the upstream prelude's `prelude` cell references would point to our own, causing all sorts of issues. The following are conflicting:
- the upstream prelude hardcodes the identifier `prelude`
- the (custom) prelude cell has to be called `prelude`
