### ISSUE TITLE
Will Buck2 work with Sun Grid Engine for remote execution?

### ISSUE THREAD

**Issue by NP95** [facebook/buck2#726]
Hi we have a codebase with mixed Python/C++ held with make duct tape. I am thinking of undertaking a study to integrating buck2 for this codebase, we have a Sun Grid Engine infra and I was wondering if this would work as a remote execution target for Buck2?

**Comment by cormacrelf** [comment]
There's nothing stopping you, but it would be a significant undertaking.

There are many places you *could* add SGE, but most are a bad idea.

- Don't add support directly to Buck2. Nobody is going to maintain that, and anyway, SGE alone is not a cache, RE is not worth it without a cache.
- Don't write a Bazel RBE implementation from scratch. Same problem. You'll need to write an action cache + content-addressed storage implementation, which is just so immense an undertaking, and other people have already done this.
- Don't shoehorn SGE queue submission into another Bazel RBE implementation as a "worker" -- you'll count "scheduled on SGE but not yet executing" time as executing, which will be weird, you'll never see how long anything truly takes to execute.
- __*Do* try to slot SGE in as the the scheduler + worker portion of another Bazel RBE implementation.__

Maybe you could implement a [nativelink](https://github.com/tracemachina/nativelink) scheduler that lays out files in NFS for the job, simply uses qsub to execute, and doesn't use any nativelink workers. This could be done outside the nativelink binary by implementing the GRPC scheduler protocol that nativelink defines, which you could do in a language of your choice. I would talk to them about it, see what they say, I don't know how stable that GRPC API is and it may only be intended to spread nativelink over multiple machines. But I think that's the right level to do this kind of work at.

**Comment by NP95** [comment]
Excellent points, I had ruled out 1 and 2, was considering 3 and 4. Appreciate the insights and advice, I might try and explore the nativelink option for my own education, but yeah remote execution can be postponed for later.

Thanks for the feedback, closing this issue as solved.

**Comment by cormacrelf** [comment]
I do think it would be very cool and a great use of compute resources you've already got. Good luck!
