### ISSUE TITLE
How does Buck2 handle external dependencies (crates from crates.io) for building Rust libraries?

### ISSUE THREAD

**Issue by Graian** [facebook/buck2#772]
In **Bazel**, rules like `cargo_raze` or `crate_universe_dependencies` are used to reference information from `Cargo.toml` and `Cargo.lock`. I'm curious how this is handled in **Buck2**.

**Comment by cbarrete** [comment]
You're looking for https://github.com/facebookincubator/reindeer :)

**Comment by Graian** [comment]
> You're looking for https://github.com/facebookincubator/reindeer :)

Thank you very much for providing such great resources!!
