### ISSUE TITLE
buck2.build website doesn't redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by danmx** [facebook/buck2#94]
buck2.build website doesn't redirect HTTP requests to HTTPS even though there is a valid HTTPS endpoint (valid TLS certificate).

```console
$ curl -vvv http://buck2.build/
*   Trying 104.21.12.229:80...
* Connected to buck2.build (104.21.12.229) port 80 (#0)
> GET / HTTP/1.1
> Host: buck2.build
> User-Agent: curl/7.86.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Sun, 12 Feb 2023 12:41:29 GMT
< Content-Type: text/html; charset=utf-8
[...]
```

It can be fixed by enforcing HTTPS. [Enforcing HTTPS for your GitHub Pages site](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site).

**Comment by Mdabukala** [comment]
thank you

**Comment by Mdabukala** [comment]
ok

**Comment by Mdabukala** [comment]
ok

**Comment by ndmitchell** [comment]
Following the guide, I can't find the "Enforcing HTTPS" setting that the GitHub page talks about. I'll ping some people to find out if they have it.

**Comment by ndmitchell** [comment]
I think this is done now.

**Comment by danmx** [comment]
It doesn't look fixed. I still can access the website over http

**Comment by ndmitchell** [comment]
Huh, it gave me a redirect yesterday when I checked, but now it doesn't. I'll see - something automated might be "fixing" the settings.

**Comment by ndmitchell** [comment]
Fixed again, I believe, and I now get a redirect back.

**Comment by danmx** [comment]
it's working now
